/*==============================================================================
 AVIDIA BANK - CATALOG SCORECARD

 Purpose:
   Create one compact scorecard view for the seven Block 5 governance
   dimensions. The view reuses existing governance evidence and does not
   persist duplicate scoring data.

 Output:
   One row for each dimension:
   OWNED, DEFINED, TRACEABLE, TRUSTED, SECURE, ADOPTED, RECONCILED.
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE OR REPLACE VIEW GOVERNANCE.CATALOG.CATALOG_SCORECARD
COMMENT = 'Seven-dimension governance scorecard over the existing Avidia catalog evidence.'
AS
WITH CATALOG_OBJECTS AS
(
    SELECT
        OBJECT_FQN,
        ANY_VALUE(DATA_OWNER) AS DATA_OWNER,
        ANY_VALUE(DATA_STEWARD) AS DATA_STEWARD,
        ANY_VALUE(CERTIFICATION) AS CERTIFICATION,
        ANY_VALUE(QUERY_COUNT_SINCE_CREATION) AS QUERY_COUNT_SINCE_CREATION
    FROM GOVERNANCE.CATALOG.V_STREAMLIT_CATALOG
    GROUP BY OBJECT_FQN
),

CATALOG_COLUMNS AS
(
    SELECT
        OBJECT_FQN,
        COLUMN_NAME,
        DESCRIPTION,
        CLASSIFICATION
    FROM GOVERNANCE.CATALOG.V_STREAMLIT_CATALOG
),

CERTIFIED_OBJECTS AS
(
    SELECT OBJECT_FQN
    FROM CATALOG_OBJECTS
    WHERE CERTIFICATION = 'CERTIFIED'
),

LATEST_LINEAGE AS
(
    SELECT *
    FROM GOVERNANCE.CATALOG.LINEAGE_EDGE
    QUALIFY DENSE_RANK() OVER
    (
        PARTITION BY ROOT_OBJECT
        ORDER BY SNAPSHOT_AT DESC
    ) = 1
),

LINEAGE_SUMMARY AS
(
    SELECT
        ROOT_OBJECT AS OBJECT_FQN,
        COUNT_IF(
            DIRECTION = 'UPSTREAM'
            AND SOURCE_OBJECT_DOMAIN = 'TABLE'
            AND SOURCE_OBJECT IS NOT NULL
        ) AS UPSTREAM_EDGE_COUNT
    FROM LATEST_LINEAGE
    GROUP BY ROOT_OBJECT
),

LATEST_DQ AS
(
    SELECT *
    FROM GOVERNANCE.DQ.DQ_RESULT
    QUALIFY DENSE_RANK() OVER
    (
        PARTITION BY OBJECT_FQN
        ORDER BY MEASURED_AT DESC, RUN_ID DESC
    ) = 1
),

DQ_SUMMARY AS
(
    SELECT
        OBJECT_FQN,
        COUNT(*) AS TOTAL_CHECKS,
        COUNT(DISTINCT QUALITY_DIMENSION) AS DISTINCT_DIMENSIONS,
        COUNT_IF(STATUS = 'PASS') AS PASSED_CHECKS,
        COUNT_IF(STATUS = 'FAIL') AS FAILED_CHECKS
    FROM LATEST_DQ
    WHERE QUALITY_DIMENSION IN
    (
        'COMPLETENESS',
        'UNIQUENESS',
        'VALIDITY',
        'CONSISTENCY',
        'TIMELINESS',
        'ACCURACY'
    )
    GROUP BY OBJECT_FQN
),

ACCURACY_SUMMARY AS
(
    SELECT
        OBJECT_FQN,
        MAX(IFF(STATUS = 'PASS', 1, 0)) AS ACCURACY_PASS_FLAG
    FROM LATEST_DQ
    WHERE QUALITY_DIMENSION = 'ACCURACY'
    GROUP BY OBJECT_FQN
),

CLASSIFIED_COLUMNS AS
(
    SELECT
        OBJECT_FQN,
        COLUMN_NAME,
        CLASSIFICATION
    FROM CATALOG_COLUMNS
    WHERE CLASSIFICATION <> 'NOT CLASSIFIED'
),

MART_POLICY_REFS AS
(
    SELECT
        'ANALYTICS.MARTS.CUSTOMER_360' AS OBJECT_FQN,
        REF_COLUMN_NAME AS COLUMN_NAME,
        POLICY_STATUS
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.POLICY_REFERENCES
        (
            REF_ENTITY_NAME => 'ANALYTICS.MARTS.CUSTOMER_360',
            REF_ENTITY_DOMAIN => 'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'

    UNION ALL

    SELECT
        'ANALYTICS.MARTS.DEPOSITS_DAILY',
        REF_COLUMN_NAME,
        POLICY_STATUS
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.POLICY_REFERENCES
        (
            REF_ENTITY_NAME => 'ANALYTICS.MARTS.DEPOSITS_DAILY',
            REF_ENTITY_DOMAIN => 'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'

    UNION ALL

    SELECT
        'ANALYTICS.MARTS.LOAN_PORTFOLIO',
        REF_COLUMN_NAME,
        POLICY_STATUS
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.POLICY_REFERENCES
        (
            REF_ENTITY_NAME => 'ANALYTICS.MARTS.LOAN_PORTFOLIO',
            REF_ENTITY_DOMAIN => 'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'
),

SCORES AS
(
    SELECT
        'OWNED' AS DIMENSION,
        COUNT_IF(DATA_OWNER <> 'NOT AVAILABLE' AND DATA_STEWARD <> 'NOT AVAILABLE') AS NUMERATOR,
        COUNT(*) AS DENOMINATOR,
        'Catalog objects with both DATA_OWNER and DATA_STEWARD.' AS DESCRIPTION
    FROM CATALOG_OBJECTS

    UNION ALL

    SELECT
        'DEFINED',
        COUNT_IF(DESCRIPTION <> 'NOT AVAILABLE'),
        COUNT(*),
        'Catalog columns with an approved non-empty description/comment.'
    FROM CATALOG_COLUMNS

    UNION ALL

    SELECT
        'TRACEABLE',
        COUNT_IF(COALESCE(L.UPSTREAM_EDGE_COUNT, 0) > 0),
        COUNT(*),
        'Certified MART objects with upstream lineage evidence.'
    FROM CERTIFIED_OBJECTS AS C
    LEFT JOIN LINEAGE_SUMMARY AS L
        ON L.OBJECT_FQN = C.OBJECT_FQN

    UNION ALL

    SELECT
        'TRUSTED',
        COUNT_IF(
            D.TOTAL_CHECKS = 6
            AND D.DISTINCT_DIMENSIONS = 6
            AND D.PASSED_CHECKS = 6
            AND D.FAILED_CHECKS = 0
        ),
        COUNT(*),
        'Certified MARTs whose latest six DQ dimensions all pass.'
    FROM CERTIFIED_OBJECTS AS C
    INNER JOIN DQ_SUMMARY AS D
        ON D.OBJECT_FQN = C.OBJECT_FQN

    UNION ALL

    SELECT
        'SECURE',
        COUNT_IF(P.COLUMN_NAME IS NOT NULL AND P.POLICY_STATUS = 'ACTIVE'),
        COUNT(*),
        'Confirmed classified MART columns with active tag-based protection.'
    FROM CLASSIFIED_COLUMNS AS C
    LEFT JOIN MART_POLICY_REFS AS P
        ON P.OBJECT_FQN = C.OBJECT_FQN
       AND P.COLUMN_NAME = C.COLUMN_NAME
       AND P.POLICY_STATUS = 'ACTIVE'

    UNION ALL

    SELECT
        'ADOPTED',
        COUNT_IF(QUERY_COUNT_SINCE_CREATION > 0),
        COUNT(*),
        'Certified catalog objects with at least one observed usage event.'
    FROM CERTIFIED_OBJECTS AS C
    INNER JOIN CATALOG_OBJECTS AS O
        ON O.OBJECT_FQN = C.OBJECT_FQN

    UNION ALL

    SELECT
        'RECONCILED',
        COUNT_IF(A.ACCURACY_PASS_FLAG = 1),
        COUNT(*),
        'Certified MARTs whose latest ACCURACY reconciliation DQ check passes.'
    FROM CERTIFIED_OBJECTS AS C
    INNER JOIN ACCURACY_SUMMARY AS A
        ON A.OBJECT_FQN = C.OBJECT_FQN
),

FINAL_SCORES AS
(
    SELECT
        DIMENSION,
        NUMERATOR,
        DENOMINATOR,
        ROUND(NUMERATOR * 100.0 / NULLIF(DENOMINATOR, 0), 2) AS SCORE_PCT,
        IFF(NUMERATOR = DENOMINATOR AND DENOMINATOR > 0, 'PASS', 'GAP') AS STATUS,
        DESCRIPTION
    FROM SCORES
)

SELECT
    DIMENSION,
    NUMERATOR,
    DENOMINATOR,
    SCORE_PCT,
    STATUS,
    DESCRIPTION
FROM FINAL_SCORES;

GRANT SELECT
ON VIEW GOVERNANCE.CATALOG.CATALOG_SCORECARD
TO ROLE CATALOG_APP_ROLE;

SELECT *
FROM GOVERNANCE.CATALOG.CATALOG_SCORECARD
ORDER BY
    CASE DIMENSION
        WHEN 'OWNED' THEN 1
        WHEN 'DEFINED' THEN 2
        WHEN 'TRACEABLE' THEN 3
        WHEN 'TRUSTED' THEN 4
        WHEN 'SECURE' THEN 5
        WHEN 'ADOPTED' THEN 6
        WHEN 'RECONCILED' THEN 7
    END;
