/*==============================================================================
 AVIDIA BANK - VALIDATE CATALOG SCORECARD

 Purpose:
   Provide simple evidence queries for the seven-dimension catalog scorecard.
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

SELECT *
FROM GOVERNANCE.CATALOG.CATALOG_SCORECARD
ORDER BY
    CASE DIMENSION
        WHEN 'OWNED' THEN 1
        WHEN 'DEFINED' THEN 2
        WHEN 'TRACEABLE' THEN 3
        WHEN 'TRUSTED' THEN 4
        WHEN 'SECURE' THEN 5
        WHEN 'ADOPTED' THEN 6
        WHEN 'RECONCILED' THEN 7
    END;

WITH EXPECTED_DIMENSIONS AS
(
    SELECT COLUMN1::VARCHAR AS DIMENSION
    FROM VALUES
        ('OWNED'),
        ('DEFINED'),
        ('TRACEABLE'),
        ('TRUSTED'),
        ('SECURE'),
        ('ADOPTED'),
        ('RECONCILED')
)
SELECT
    COUNT(S.DIMENSION) AS ACTUAL_DIMENSIONS,
    COUNT(E.DIMENSION) AS EXPECTED_DIMENSIONS,
    IFF(COUNT(S.DIMENSION) = 7, 'PASS', 'FAIL') AS DIMENSION_COUNT_STATUS
FROM EXPECTED_DIMENSIONS AS E
LEFT JOIN GOVERNANCE.CATALOG.CATALOG_SCORECARD AS S
    ON S.DIMENSION = E.DIMENSION;

WITH EXPECTED_DIMENSIONS AS
(
    SELECT COLUMN1::VARCHAR AS DIMENSION
    FROM VALUES
        ('OWNED'),
        ('DEFINED'),
        ('TRACEABLE'),
        ('TRUSTED'),
        ('SECURE'),
        ('ADOPTED'),
        ('RECONCILED')
)
SELECT
    E.DIMENSION,
    IFF(S.DIMENSION IS NULL, 'MISSING', 'PRESENT') AS DIMENSION_STATUS
FROM EXPECTED_DIMENSIONS AS E
LEFT JOIN GOVERNANCE.CATALOG.CATALOG_SCORECARD AS S
    ON S.DIMENSION = E.DIMENSION
ORDER BY E.DIMENSION;

SELECT
    DIMENSION,
    NUMERATOR,
    DENOMINATOR
FROM GOVERNANCE.CATALOG.CATALOG_SCORECARD
WHERE NUMERATOR > DENOMINATOR;

SELECT
    DIMENSION,
    SCORE_PCT
FROM GOVERNANCE.CATALOG.CATALOG_SCORECARD
WHERE DENOMINATOR > 0
  AND (SCORE_PCT < 0 OR SCORE_PCT > 100);

-- TRUSTED evidence: latest DQ coverage for certified marts.
WITH CERTIFIED_OBJECTS AS
(
    SELECT DISTINCT OBJECT_FQN
    FROM GOVERNANCE.CATALOG.V_STREAMLIT_CATALOG
    WHERE CERTIFICATION = 'CERTIFIED'
),
LATEST_DQ AS
(
    SELECT *
    FROM GOVERNANCE.DQ.DQ_RESULT
    QUALIFY DENSE_RANK() OVER
    (
        PARTITION BY OBJECT_FQN
        ORDER BY MEASURED_AT DESC, RUN_ID DESC
    ) = 1
)
SELECT
    C.OBJECT_FQN,
    COUNT(D.QUALITY_DIMENSION) AS TOTAL_CHECKS,
    COUNT(DISTINCT D.QUALITY_DIMENSION) AS DISTINCT_DIMENSIONS,
    COUNT_IF(D.STATUS = 'PASS') AS PASSED_CHECKS,
    COUNT_IF(D.STATUS = 'FAIL') AS FAILED_CHECKS
FROM CERTIFIED_OBJECTS AS C
LEFT JOIN LATEST_DQ AS D
    ON D.OBJECT_FQN = C.OBJECT_FQN
   AND D.QUALITY_DIMENSION IN
   (
       'COMPLETENESS',
       'UNIQUENESS',
       'VALIDITY',
       'CONSISTENCY',
       'TIMELINESS',
       'ACCURACY'
   )
GROUP BY C.OBJECT_FQN
ORDER BY C.OBJECT_FQN;

-- RECONCILED evidence: latest ACCURACY result for certified marts.
WITH CERTIFIED_OBJECTS AS
(
    SELECT DISTINCT OBJECT_FQN
    FROM GOVERNANCE.CATALOG.V_STREAMLIT_CATALOG
    WHERE CERTIFICATION = 'CERTIFIED'
),
LATEST_DQ AS
(
    SELECT *
    FROM GOVERNANCE.DQ.DQ_RESULT
    WHERE QUALITY_DIMENSION = 'ACCURACY'
    QUALIFY DENSE_RANK() OVER
    (
        PARTITION BY OBJECT_FQN
        ORDER BY MEASURED_AT DESC, RUN_ID DESC
    ) = 1
)
SELECT
    C.OBJECT_FQN,
    D.CHECK_NAME,
    D.STATUS,
    D.METRIC_VALUE,
    D.THRESHOLD_VALUE,
    D.MEASURED_AT
FROM CERTIFIED_OBJECTS AS C
LEFT JOIN LATEST_DQ AS D
    ON D.OBJECT_FQN = C.OBJECT_FQN
ORDER BY C.OBJECT_FQN;

-- SECURE evidence: classified MART columns and active policy references.
WITH CLASSIFIED_COLUMNS AS
(
    SELECT DISTINCT
        OBJECT_FQN,
        COLUMN_NAME,
        CLASSIFICATION
    FROM GOVERNANCE.CATALOG.V_STREAMLIT_CATALOG
    WHERE CLASSIFICATION <> 'NOT CLASSIFIED'
),
MART_POLICY_REFS AS
(
    SELECT
        'ANALYTICS.MARTS.CUSTOMER_360' AS OBJECT_FQN,
        REF_COLUMN_NAME AS COLUMN_NAME,
        POLICY_STATUS
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.POLICY_REFERENCES
        (
            REF_ENTITY_NAME => 'ANALYTICS.MARTS.CUSTOMER_360',
            REF_ENTITY_DOMAIN => 'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'

    UNION ALL

    SELECT
        'ANALYTICS.MARTS.DEPOSITS_DAILY',
        REF_COLUMN_NAME,
        POLICY_STATUS
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.POLICY_REFERENCES
        (
            REF_ENTITY_NAME => 'ANALYTICS.MARTS.DEPOSITS_DAILY',
            REF_ENTITY_DOMAIN => 'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'

    UNION ALL

    SELECT
        'ANALYTICS.MARTS.LOAN_PORTFOLIO',
        REF_COLUMN_NAME,
        POLICY_STATUS
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.POLICY_REFERENCES
        (
            REF_ENTITY_NAME => 'ANALYTICS.MARTS.LOAN_PORTFOLIO',
            REF_ENTITY_DOMAIN => 'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'
)
SELECT
    C.OBJECT_FQN,
    C.COLUMN_NAME,
    C.CLASSIFICATION,
    COALESCE(P.POLICY_STATUS, 'NO_ACTIVE_POLICY') AS POLICY_STATUS
FROM CLASSIFIED_COLUMNS AS C
LEFT JOIN MART_POLICY_REFS AS P
    ON P.OBJECT_FQN = C.OBJECT_FQN
   AND P.COLUMN_NAME = C.COLUMN_NAME
   AND P.POLICY_STATUS = 'ACTIVE'
ORDER BY
    C.OBJECT_FQN,
    C.COLUMN_NAME;

-- ADOPTED evidence: certified objects with observed usage.
SELECT DISTINCT
    OBJECT_FQN,
    CERTIFICATION,
    QUERY_COUNT_SINCE_CREATION,
    DISTINCT_ROLES_SINCE_CREATION
FROM GOVERNANCE.CATALOG.V_STREAMLIT_CATALOG
WHERE CERTIFICATION = 'CERTIFIED'
ORDER BY OBJECT_FQN;
