CALL GOVERNANCE.CATALOG.HARVEST_METADATA();

--Validate OBJECT_CATALOG

SELECT
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    OBJECT_TYPE,
    OBJECT_OWNER,
    ROW_COUNT,
    SOURCE_METADATA,
    HARVESTED_AT
FROM GOVERNANCE.CATALOG.OBJECT_CATALOG
ORDER BY
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME;

--Validate COLUMN_CATALOG

SELECT
    DATABASE_NAME,
    SCHEMA_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    ORDINAL_POSITION,
    DATA_TYPE,
    IS_NULLABLE,
    COMMENT,
    SOURCE_METADATA
FROM GOVERNANCE.CATALOG.COLUMN_CATALOG
ORDER BY
    DATABASE_NAME,
    SCHEMA_NAME,
    TABLE_NAME,
    ORDINAL_POSITION;

--Check for duplicate metadata
-- For Objects
SELECT
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    COUNT(*) AS RECORD_COUNT
FROM GOVERNANCE.CATALOG.OBJECT_CATALOG
GROUP BY
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME
HAVING COUNT(*) > 1;


--For columns:

SELECT
    DATABASE_NAME,
    SCHEMA_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    COUNT(*) AS RECORD_COUNT
FROM GOVERNANCE.CATALOG.COLUMN_CATALOG
GROUP BY
    DATABASE_NAME,
    SCHEMA_NAME,
    TABLE_NAME,
    COLUMN_NAME
HAVING COUNT(*) > 1;


-- Prove idempotency

CALL GOVERNANCE.CATALOG.HARVEST_METADATA();

SELECT COUNT(*)
FROM GOVERNANCE.CATALOG.OBJECT_CATALOG;

SELECT COUNT(*)
FROM GOVERNANCE.CATALOG.COLUMN_CATALOG;


CALL GOVERNANCE.CATALOG.HARVEST_METADATA();

SELECT COUNT(*)
FROM GOVERNANCE.CATALOG.OBJECT_CATALOG;

SELECT COUNT(*)
FROM GOVERNANCE.CATALOG.COLUMN_CATALOG;



