USE ROLE ACCOUNTADMIN;

GRANT USAGE
ON DATABASE GOVERNANCE
TO ROLE SYSADMIN;

GRANT CREATE SCHEMA
ON DATABASE GOVERNANCE
TO ROLE SYSADMIN;

GRANT USAGE
ON DATABASE GOVERNANCE
TO ROLE SYSADMIN;

GRANT USAGE
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE SYSADMIN;

GRANT CREATE TABLE
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE SYSADMIN;

--GRANT USAGE ON DATABASE GOVERNANCE TO ROLE SYSADMIN;
--GRANT USAGE ON SCHEMA GOVERNANCE.CATALOG TO ROLE SYSADMIN;
--GRANT CREATE TABLE ON SCHEMA GOVERNANCE.CATALOG TO ROLE SYSADMIN;


SHOW GRANTS TO ROLE SYSADMIN;
SHOW GRANTS ON SCHEMA GOVERNANCE.CATALOG;


