USE ROLE ACCOUNTADMIN;

GRANT USAGE
ON DATABASE GOVERNANCE
TO ROLE SYSADMIN;

GRANT CREATE SCHEMA
ON DATABASE GOVERNANCE
TO ROLE SYSADMIN;

GRANT USAGE
ON DATABASE GOVERNANCE
TO ROLE SYSADMIN;

GRANT USAGE
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE SYSADMIN;

GRANT CREATE TABLE
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE SYSADMIN;

GRANT USAGE ON DATABASE GOVERNANCE TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA GOVERNANCE.CATALOG TO ROLE SYSADMIN;
GRANT CREATE TABLE ON SCHEMA GOVERNANCE.CATALOG TO ROLE SYSADMIN;
GRANT CREATE PROCEDURE ON SCHEMA GOVERNANCE.CATALOG TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA GOVERNANCE.TAGS TO ROLE SYSADMIN;
GRANT CREATE TAG ON SCHEMA GOVERNANCE.TAGS TO ROLE SYSADMIN;


SHOW GRANTS TO ROLE SYSADMIN;
SHOW GRANTS ON SCHEMA GOVERNANCE.CATALOG;
SHOW GRANTS ON SCHEMA GOVERNANCE.TAGS;

-- for a GOVERNANCE metadata store harvested from both INFORMATION_SCHEMA and ACCOUNT_USAGE by a stored procedure that will subsequently be run by a Task.

GRANT IMPORTED PRIVILEGES
ON DATABASE SNOWFLAKE
TO ROLE DATA_GOVERNANCE_ADMIN;


GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;


-- ============================================================================
-- METADATA HARVEST TASK PRIVILEGES
-- ============================================================================


-- Allow governance role to create tasks inside GOVERNANCE.CATALOG.
GRANT CREATE TASK
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;


-- Required because the task uses the existing governance warehouse.
GRANT USAGE
ON WAREHOUSE WH_GOVERNANCE_XS
TO ROLE DATA_GOVERNANCE_ADMIN;


-- Required for tasks owned by DATA_GOVERNANCE_ADMIN to execute.
GRANT EXECUTE TASK
ON ACCOUNT
TO ROLE DATA_GOVERNANCE_ADMIN;


-- ============================================================================
-- DATA DICTIONARY INGESTION PRIVILEGES
-- ============================================================================

GRANT CREATE STAGE
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT CREATE FILE FORMAT
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT OWNERSHIP
ON ALL TABLES IN SCHEMA RAW.BANKING
TO ROLE DATA_ENGINEER
COPY CURRENT GRANTS;


GRANT USAGE
ON DATABASE RAW
TO ROLE DATA_ENGINEER;

GRANT USAGE
ON SCHEMA RAW.BANKING
TO ROLE DATA_ENGINEER;

GRANT CREATE TABLE
ON SCHEMA RAW.BANKING
TO ROLE DATA_ENGINEER;

GRANT CREATE PROCEDURE
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE
ON DATABASE GOVERNANCE
TO ROLE DATA_ENGINEER;

GRANT USAGE
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_ENGINEER;

-- DATA_DICTIONARY is created later by metadata/01_create_governance_schemas.sql.
-- Its specific SELECT grant is applied there after the table exists so a fresh
-- metadata rebuild does not fail on an object that has not been created yet.


