/*==============================================================================
 AVIDIA BANK - BLOCK 4 LINEAGE PERMISSIONS

 Purpose:
   Minimum privileges for native Snowflake lineage, Account Usage evidence,
   lineage snapshot tables and the lineage snapshot task.

 Runtime role:
   DATA_GOVERNANCE_ADMIN
==============================================================================*/

USE ROLE SECURITYADMIN;

-- Native lineage visibility.
GRANT VIEW LINEAGE ON ACCOUNT
TO ROLE DATA_GOVERNANCE_ADMIN;

-- Account Usage evidence for OBJECT_DEPENDENCIES and ACCESS_HISTORY.
GRANT DATABASE ROLE SNOWFLAKE.OBJECT_VIEWER
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER
TO ROLE DATA_GOVERNANCE_ADMIN;

-- Existing governance warehouse.
GRANT USAGE
ON WAREHOUSE WH_GOVERNANCE_XS
TO ROLE DATA_GOVERNANCE_ADMIN;

-- Relevant RAW, STAGING and MART lineage objects.
GRANT USAGE
ON DATABASE RAW
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE
ON SCHEMA RAW.BANKING
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT REFERENCES
ON TABLE RAW.BANKING.ACCOUNT_DAILY_BALANCE
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT REFERENCES
ON TABLE RAW.BANKING.ACCOUNT
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT REFERENCES
ON TABLE RAW.BANKING.CUSTOMER
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT REFERENCES
ON TABLE RAW.BANKING.PRODUCT
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT REFERENCES
ON TABLE RAW.BANKING.BRANCH
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE
ON DATABASE ANALYTICS
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE
ON SCHEMA ANALYTICS.STAGING
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE
ON SCHEMA ANALYTICS.MARTS
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT REFERENCES
ON TABLE ANALYTICS.STAGING.STG_ACCOUNT_DAILY_BALANCE
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT REFERENCES
ON TABLE ANALYTICS.STAGING.STG_ACCOUNT
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT REFERENCES
ON TABLE ANALYTICS.STAGING.STG_CUSTOMER
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT REFERENCES
ON TABLE ANALYTICS.STAGING.STG_PRODUCT
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT REFERENCES
ON TABLE ANALYTICS.STAGING.STG_BRANCH
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT REFERENCES
ON TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
TO ROLE DATA_GOVERNANCE_ADMIN;

-- Snapshot tables and task.
GRANT USAGE
ON DATABASE GOVERNANCE
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT CREATE TABLE
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT CREATE TASK
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT EXECUTE TASK
ON ACCOUNT
TO ROLE DATA_GOVERNANCE_ADMIN;

SHOW GRANTS TO ROLE DATA_GOVERNANCE_ADMIN;
