/*==============================================================================
 AVIDIA BANK - NATIVE LINEAGE QUERIES

 Purpose:
   Query native Snowflake lineage and supporting Account Usage evidence for
   ANALYTICS.MARTS.DEPOSITS_DAILY.
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;

-- A. Table-level upstream lineage. Expected to include STAGING and RAW edges.
SELECT
    DISTANCE,
    SOURCE_OBJECT_DATABASE || '.' || SOURCE_OBJECT_SCHEMA || '.'
        || SOURCE_OBJECT_NAME AS SOURCE_OBJECT,
    SOURCE_OBJECT_DOMAIN,
    TARGET_OBJECT_DATABASE || '.' || TARGET_OBJECT_SCHEMA || '.'
        || TARGET_OBJECT_NAME AS TARGET_OBJECT,
    TARGET_OBJECT_DOMAIN,
    PROCESS:query_id::VARCHAR AS PROCESS_QUERY_ID,
    SOURCE_DETAILS:origin::VARCHAR AS SOURCE_ORIGIN,
    TARGET_DETAILS:origin::VARCHAR AS TARGET_ORIGIN
FROM TABLE
(
    SNOWFLAKE.CORE.GET_LINEAGE
    (
        'ANALYTICS.MARTS.DEPOSITS_DAILY',
        'TABLE',
        'UPSTREAM',
        5
    )
)
ORDER BY DISTANCE, SOURCE_OBJECT, TARGET_OBJECT;

-- B. Table-level downstream native lineage. The downstream external endpoint
-- is represented only as metadata in LINEAGE_EDGE_EXTERNAL, so native
-- downstream may correctly return no rows.
SELECT
    DISTANCE,
    SOURCE_OBJECT_DATABASE || '.' || SOURCE_OBJECT_SCHEMA || '.'
        || SOURCE_OBJECT_NAME AS SOURCE_OBJECT,
    SOURCE_OBJECT_DOMAIN,
    TARGET_OBJECT_DATABASE || '.' || TARGET_OBJECT_SCHEMA || '.'
        || TARGET_OBJECT_NAME AS TARGET_OBJECT,
    TARGET_OBJECT_DOMAIN,
    PROCESS:query_id::VARCHAR AS PROCESS_QUERY_ID
FROM TABLE
(
    SNOWFLAKE.CORE.GET_LINEAGE
    (
        'ANALYTICS.MARTS.DEPOSITS_DAILY',
        'TABLE',
        'DOWNSTREAM',
        5
    )
)
ORDER BY DISTANCE, SOURCE_OBJECT, TARGET_OBJECT;

-- C. OBJECT_DEPENDENCIES evidence. This is supporting evidence only; Account
-- Usage can lag and data-copy operations may not appear as dependencies.
SELECT
    REFERENCED_DATABASE,
    REFERENCED_SCHEMA,
    REFERENCED_OBJECT_NAME,
    REFERENCED_OBJECT_DOMAIN,
    REFERENCING_DATABASE,
    REFERENCING_SCHEMA,
    REFERENCING_OBJECT_NAME,
    REFERENCING_OBJECT_DOMAIN,
    DEPENDENCY_TYPE
FROM SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES
WHERE
    REFERENCED_OBJECT_NAME IN
    (
        'ACCOUNT_DAILY_BALANCE',
        'ACCOUNT',
        'CUSTOMER',
        'PRODUCT',
        'BRANCH',
        'STG_ACCOUNT_DAILY_BALANCE',
        'STG_ACCOUNT',
        'STG_CUSTOMER',
        'STG_PRODUCT',
        'STG_BRANCH'
    )
    OR REFERENCING_OBJECT_NAME = 'DEPOSITS_DAILY'
ORDER BY
    REFERENCED_DATABASE,
    REFERENCED_SCHEMA,
    REFERENCED_OBJECT_NAME,
    REFERENCING_DATABASE,
    REFERENCING_SCHEMA,
    REFERENCING_OBJECT_NAME;

-- D. ACCESS_HISTORY evidence. Expect latency in ACCOUNT_USAGE. The query
-- intentionally searches both accessed and modified objects for the chain.
SELECT
    QUERY_START_TIME,
    USER_NAME,
    QUERY_ID,
    DIRECT_OBJECTS_ACCESSED,
    BASE_OBJECTS_ACCESSED,
    OBJECTS_MODIFIED
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD('DAY', -7, CURRENT_TIMESTAMP())
  AND
  (
      DIRECT_OBJECTS_ACCESSED::VARCHAR ILIKE '%DEPOSITS_DAILY%'
      OR BASE_OBJECTS_ACCESSED::VARCHAR ILIKE '%DEPOSITS_DAILY%'
      OR OBJECTS_MODIFIED::VARCHAR ILIKE '%DEPOSITS_DAILY%'
      OR DIRECT_OBJECTS_ACCESSED::VARCHAR ILIKE '%STG_ACCOUNT_DAILY_BALANCE%'
      OR BASE_OBJECTS_ACCESSED::VARCHAR ILIKE '%STG_ACCOUNT_DAILY_BALANCE%'
      OR OBJECTS_MODIFIED::VARCHAR ILIKE '%STG_ACCOUNT_DAILY_BALANCE%'
      OR DIRECT_OBJECTS_ACCESSED::VARCHAR ILIKE '%ACCOUNT_DAILY_BALANCE%'
      OR BASE_OBJECTS_ACCESSED::VARCHAR ILIKE '%ACCOUNT_DAILY_BALANCE%'
      OR OBJECTS_MODIFIED::VARCHAR ILIKE '%ACCOUNT_DAILY_BALANCE%'
  )
ORDER BY QUERY_START_TIME DESC
LIMIT 50;
