/*==============================================================================
 AVIDIA BANK - LINEAGE SNAPSHOT TASK

 Purpose:
   Create a daily task that snapshots native Snowflake lineage for
   DEPOSITS_DAILY into GOVERNANCE.CATALOG.LINEAGE_EDGE.

 Design:
   - GET_LINEAGE remains the source of truth.
   - LINEAGE_EDGE stores historical evidence snapshots for review packs.
   - Both upstream and downstream directions are captured.
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE OR REPLACE TASK GOVERNANCE.CATALOG.SNAPSHOT_DEPOSITS_DAILY_LINEAGE_TASK
    WAREHOUSE = WH_GOVERNANCE_XS
    SCHEDULE = 'USING CRON 0 6 * * * UTC'
    COMMENT = 'Daily snapshot of native Snowflake lineage for ANALYTICS.MARTS.DEPOSITS_DAILY.'
AS
INSERT INTO GOVERNANCE.CATALOG.LINEAGE_EDGE
(
    SNAPSHOT_ID,
    SNAPSHOT_AT,
    ROOT_OBJECT,
    DIRECTION,
    DISTANCE,
    SOURCE_OBJECT,
    SOURCE_OBJECT_DATABASE,
    SOURCE_OBJECT_SCHEMA,
    SOURCE_OBJECT_NAME,
    SOURCE_OBJECT_DOMAIN,
    SOURCE_COLUMN,
    SOURCE_STATUS,
    SOURCE_ORIGIN,
    TARGET_OBJECT,
    TARGET_OBJECT_DATABASE,
    TARGET_OBJECT_SCHEMA,
    TARGET_OBJECT_NAME,
    TARGET_OBJECT_DOMAIN,
    TARGET_COLUMN,
    TARGET_STATUS,
    TARGET_ORIGIN,
    PROCESS,
    SOURCE_DETAILS,
    TARGET_DETAILS
)
WITH SNAPSHOT_CONTEXT AS
(
    SELECT
        UUID_STRING() AS SNAPSHOT_ID,
        CURRENT_TIMESTAMP() AS SNAPSHOT_AT
),

LINEAGE_ROWS AS
(
    SELECT
        'UPSTREAM' AS DIRECTION,
        *
    FROM TABLE
    (
        SNOWFLAKE.CORE.GET_LINEAGE
        (
            'ANALYTICS.MARTS.DEPOSITS_DAILY',
            'TABLE',
            'UPSTREAM',
            5
        )
    )

    UNION ALL

    SELECT
        'DOWNSTREAM' AS DIRECTION,
        *
    FROM TABLE
    (
        SNOWFLAKE.CORE.GET_LINEAGE
        (
            'ANALYTICS.MARTS.DEPOSITS_DAILY',
            'TABLE',
            'DOWNSTREAM',
            5
        )
    )
)
SELECT
    C.SNAPSHOT_ID,
    C.SNAPSHOT_AT,
    'ANALYTICS.MARTS.DEPOSITS_DAILY' AS ROOT_OBJECT,
    L.DIRECTION,
    L.DISTANCE,
    CONCAT_WS('.', L.SOURCE_OBJECT_DATABASE, L.SOURCE_OBJECT_SCHEMA,
        L.SOURCE_OBJECT_NAME) AS SOURCE_OBJECT,
    L.SOURCE_OBJECT_DATABASE,
    L.SOURCE_OBJECT_SCHEMA,
    L.SOURCE_OBJECT_NAME,
    L.SOURCE_OBJECT_DOMAIN,
    L.SOURCE_COLUMN_NAME,
    L.SOURCE_STATUS,
    L.SOURCE_DETAILS:origin::VARCHAR AS SOURCE_ORIGIN,
    CONCAT_WS('.', L.TARGET_OBJECT_DATABASE, L.TARGET_OBJECT_SCHEMA,
        L.TARGET_OBJECT_NAME) AS TARGET_OBJECT,
    L.TARGET_OBJECT_DATABASE,
    L.TARGET_OBJECT_SCHEMA,
    L.TARGET_OBJECT_NAME,
    L.TARGET_OBJECT_DOMAIN,
    L.TARGET_COLUMN_NAME,
    L.TARGET_STATUS,
    L.TARGET_DETAILS:origin::VARCHAR AS TARGET_ORIGIN,
    L.PROCESS,
    L.SOURCE_DETAILS,
    L.TARGET_DETAILS
FROM LINEAGE_ROWS AS L
CROSS JOIN SNAPSHOT_CONTEXT AS C;

ALTER TASK GOVERNANCE.CATALOG.SNAPSHOT_DEPOSITS_DAILY_LINEAGE_TASK RESUME;

SHOW TASKS LIKE 'SNAPSHOT_DEPOSITS_DAILY_LINEAGE_TASK' IN SCHEMA GOVERNANCE.CATALOG;
