/*==============================================================================
 AVIDIA BANK - RUN LINEAGE SNAPSHOT

 Purpose:
   Manually execute the lineage snapshot task and show the latest snapshot
   evidence. Task execution is asynchronous, so this script waits briefly.
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

SHOW TASKS LIKE 'SNAPSHOT_DEPOSITS_DAILY_LINEAGE_TASK' IN SCHEMA GOVERNANCE.CATALOG;

EXECUTE TASK GOVERNANCE.CATALOG.SNAPSHOT_DEPOSITS_DAILY_LINEAGE_TASK;

CALL SYSTEM$WAIT(10, 'SECONDS');

SELECT
    NAME,
    STATE,
    QUERY_ID,
    SCHEDULED_TIME,
    COMPLETED_TIME,
    ERROR_CODE,
    ERROR_MESSAGE
FROM TABLE
(
    INFORMATION_SCHEMA.TASK_HISTORY
    (
        TASK_NAME => 'SNAPSHOT_DEPOSITS_DAILY_LINEAGE_TASK',
        RESULT_LIMIT => 10
    )
)
ORDER BY SCHEDULED_TIME DESC;

WITH LATEST_SNAPSHOT AS
(
    SELECT SNAPSHOT_ID
    FROM GOVERNANCE.CATALOG.LINEAGE_EDGE
    WHERE ROOT_OBJECT = 'ANALYTICS.MARTS.DEPOSITS_DAILY'
    QUALIFY ROW_NUMBER() OVER (
        ORDER BY SNAPSHOT_AT DESC, SNAPSHOT_ID DESC
    ) = 1
)
SELECT
    E.SNAPSHOT_ID,
    E.SNAPSHOT_AT,
    E.DIRECTION,
    E.DISTANCE,
    E.SOURCE_OBJECT,
    E.SOURCE_OBJECT_DOMAIN,
    E.SOURCE_COLUMN,
    E.TARGET_OBJECT,
    E.TARGET_OBJECT_DOMAIN,
    E.TARGET_COLUMN,
    E.PROCESS:query_id::VARCHAR AS PROCESS_QUERY_ID
FROM GOVERNANCE.CATALOG.LINEAGE_EDGE AS E
INNER JOIN LATEST_SNAPSHOT AS L
    ON E.SNAPSHOT_ID = L.SNAPSHOT_ID
ORDER BY E.DIRECTION, E.DISTANCE, E.SOURCE_OBJECT, E.TARGET_OBJECT;

-- Native upstream snapshot should include at least one RAW source table.
WITH LATEST_SNAPSHOT AS
(
    SELECT SNAPSHOT_ID
    FROM GOVERNANCE.CATALOG.LINEAGE_EDGE
    WHERE ROOT_OBJECT = 'ANALYTICS.MARTS.DEPOSITS_DAILY'
    QUALIFY ROW_NUMBER() OVER (
        ORDER BY SNAPSHOT_AT DESC, SNAPSHOT_ID DESC
    ) = 1
)
SELECT
    COUNT(*) AS RAW_EDGE_COUNT,
    IFF(COUNT(*) > 0, 'PASS', 'FAIL') AS RAW_REACH_STATUS
FROM GOVERNANCE.CATALOG.LINEAGE_EDGE AS E
INNER JOIN LATEST_SNAPSHOT AS L
    ON E.SNAPSHOT_ID = L.SNAPSHOT_ID
WHERE E.DIRECTION = 'UPSTREAM'
  AND E.SOURCE_OBJECT_DATABASE = 'RAW';
