/*==============================================================================
 AVIDIA BANK - IMPACT ANALYSIS

 Question:
   If RAW.BANKING.ACCOUNT_DAILY_BALANCE.CLOSING_BALANCE changes, what is
   affected and who owns it?
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;

WITH NATIVE_IMPACT AS
(
    SELECT
        'RAW.BANKING.ACCOUNT_DAILY_BALANCE.CLOSING_BALANCE' AS SOURCE_COLUMN,
        TARGET_OBJECT_DATABASE || '.' || TARGET_OBJECT_SCHEMA || '.'
            || TARGET_OBJECT_NAME AS AFFECTED_OBJECT,
        TARGET_COLUMN_NAME AS AFFECTED_COLUMN,
        TARGET_OBJECT_DATABASE,
        TARGET_OBJECT_SCHEMA,
        TARGET_OBJECT_NAME,
        DISTANCE
    FROM TABLE
    (
        SNOWFLAKE.CORE.GET_LINEAGE
        (
            'RAW.BANKING.ACCOUNT_DAILY_BALANCE.CLOSING_BALANCE',
            'COLUMN',
            'DOWNSTREAM',
            5
        )
    )
),

TAG_METADATA AS
(
    SELECT
        DATABASE_NAME,
        SCHEMA_NAME,
        OBJECT_NAME,
        MAX(IFF(TAG_NAME = 'DATA_OWNER', TAG_VALUE, NULL)) AS DATA_OWNER,
        MAX(IFF(TAG_NAME = 'DATA_STEWARD', TAG_VALUE, NULL)) AS DATA_STEWARD,
        MAX(IFF(TAG_NAME = 'DOMAIN', TAG_VALUE, NULL)) AS DOMAIN,
        MAX(IFF(TAG_NAME = 'CERTIFICATION', TAG_VALUE, NULL)) AS CERTIFICATION
    FROM GOVERNANCE.CATALOG.TAG_ASSIGNMENT
    WHERE ACTIVE_FLAG = TRUE
      AND OBJECT_LEVEL IN ('TABLE', 'VIEW', 'SCHEMA', 'DATABASE', 'COLUMN')
    GROUP BY
        DATABASE_NAME,
        SCHEMA_NAME,
        OBJECT_NAME
)
SELECT
    I.SOURCE_COLUMN,
    I.AFFECTED_OBJECT,
    I.AFFECTED_COLUMN,
    I.DISTANCE,
    COALESCE(T_OBJ.DATA_OWNER, T_SCHEMA.DATA_OWNER, T_DB.DATA_OWNER)
        AS DATA_OWNER,
    COALESCE(T_OBJ.DATA_STEWARD, T_SCHEMA.DATA_STEWARD, T_DB.DATA_STEWARD)
        AS DATA_STEWARD,
    COALESCE(T_OBJ.DOMAIN, T_SCHEMA.DOMAIN, T_DB.DOMAIN)
        AS DOMAIN,
    COALESCE(T_OBJ.CERTIFICATION, T_SCHEMA.CERTIFICATION, T_DB.CERTIFICATION)
        AS CERTIFICATION
FROM NATIVE_IMPACT AS I
LEFT JOIN TAG_METADATA AS T_OBJ
    ON T_OBJ.DATABASE_NAME = I.TARGET_OBJECT_DATABASE
   AND T_OBJ.SCHEMA_NAME = I.TARGET_OBJECT_SCHEMA
   AND T_OBJ.OBJECT_NAME = I.TARGET_OBJECT_NAME
LEFT JOIN TAG_METADATA AS T_SCHEMA
    ON T_SCHEMA.DATABASE_NAME = I.TARGET_OBJECT_DATABASE
   AND T_SCHEMA.SCHEMA_NAME = I.TARGET_OBJECT_SCHEMA
   AND T_SCHEMA.OBJECT_NAME IS NULL
LEFT JOIN TAG_METADATA AS T_DB
    ON T_DB.DATABASE_NAME = I.TARGET_OBJECT_DATABASE
   AND T_DB.SCHEMA_NAME IS NULL
   AND T_DB.OBJECT_NAME IS NULL
ORDER BY I.DISTANCE, I.AFFECTED_OBJECT, I.AFFECTED_COLUMN;

-- External fallback metadata is represented only by LINEAGE_EDGE_EXTERNAL.
-- These rows do not come from native Snowflake GET_LINEAGE and do not require
-- Talend or Power BI physical resources.
SELECT
    'RAW.BANKING.ACCOUNT_DAILY_BALANCE.CLOSING_BALANCE' AS SOURCE_COLUMN,
    TARGET_OBJECT AS AFFECTED_OBJECT,
    NULL AS AFFECTED_COLUMN,
    SOURCE_SYSTEM,
    SOURCE_OBJECT,
    TARGET_SYSTEM,
    TARGET_OBJECT_TYPE,
    EDGE_TYPE,
    DESCRIPTION
FROM GOVERNANCE.CATALOG.LINEAGE_EDGE_EXTERNAL
WHERE SOURCE_OBJECT = 'ANALYTICS.MARTS.DEPOSITS_DAILY'
  AND TARGET_OBJECT = 'POWER_BI_DEPOSITS_MODEL';
