/*==============================================================================
 AVIDIA BANK - VALIDATE LINEAGE

 Purpose:
   Evidence queries for Block 4 lineage acceptance criteria.
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

-- 1-4. Native table lineage exists and reaches STAGING and RAW.
WITH UPSTREAM_LINEAGE AS
(
    SELECT *
    FROM TABLE
    (
        SNOWFLAKE.CORE.GET_LINEAGE
        (
            'ANALYTICS.MARTS.DEPOSITS_DAILY',
            'TABLE',
            'UPSTREAM',
            5
        )
    )
),
TABLE_LINEAGE_COUNTS AS
(
    SELECT
        COUNT(*) AS NATIVE_UPSTREAM_EDGE_COUNT,
        COUNT_IF(SOURCE_OBJECT_DATABASE = 'ANALYTICS'
                 AND SOURCE_OBJECT_SCHEMA = 'STAGING') AS STAGING_EDGE_COUNT,
        COUNT_IF(SOURCE_OBJECT_DATABASE = 'RAW') AS RAW_EDGE_COUNT
    FROM UPSTREAM_LINEAGE
)
SELECT
    NATIVE_UPSTREAM_EDGE_COUNT,
    STAGING_EDGE_COUNT,
    RAW_EDGE_COUNT,
    IFF(NATIVE_UPSTREAM_EDGE_COUNT > 0, 'PASS', 'FAIL')
        AS TABLE_LEVEL_LINEAGE_STATUS,
    IFF(STAGING_EDGE_COUNT > 0, 'PASS', 'FAIL') AS STAGING_REACH_STATUS,
    IFF(RAW_EDGE_COUNT > 0, 'PASS', 'FAIL') AS RAW_REACH_STATUS
FROM TABLE_LINEAGE_COUNTS;

-- 5. Column-level lineage for the deposit measure.
WITH COLUMN_TRACE AS
(
    SELECT *
    FROM TABLE
    (
        SNOWFLAKE.CORE.GET_LINEAGE
        (
            'ANALYTICS.MARTS.DEPOSITS_DAILY.CLOSING_BALANCE',
            'COLUMN',
            'UPSTREAM',
            5
        )
    )
),
COLUMN_TRACE_COUNTS AS
(
    SELECT
        COUNT(*) AS COLUMN_EDGE_COUNT,
        COUNT_IF(SOURCE_OBJECT_DATABASE = 'RAW'
                 AND SOURCE_OBJECT_NAME = 'ACCOUNT_DAILY_BALANCE'
                 AND SOURCE_COLUMN_NAME = 'CLOSING_BALANCE')
            AS RAW_COLUMN_EDGE_COUNT
    FROM COLUMN_TRACE
)
SELECT
    COLUMN_EDGE_COUNT,
    RAW_COLUMN_EDGE_COUNT,
    IFF(COLUMN_EDGE_COUNT > 0, 'PASS', 'FAIL') AS COLUMN_LINEAGE_STATUS,
    IFF(RAW_COLUMN_EDGE_COUNT > 0, 'PASS', 'FAIL') AS RAW_COLUMN_TRACE_STATUS
FROM COLUMN_TRACE_COUNTS;

-- 6-7. Latest snapshot populated by the Task.
WITH LATEST_SNAPSHOT AS
(
    SELECT SNAPSHOT_ID, SNAPSHOT_AT
    FROM
    (
        SELECT SNAPSHOT_ID, MAX(SNAPSHOT_AT) AS SNAPSHOT_AT
        FROM GOVERNANCE.CATALOG.LINEAGE_EDGE
        WHERE ROOT_OBJECT = 'ANALYTICS.MARTS.DEPOSITS_DAILY'
        GROUP BY SNAPSHOT_ID
    )
    QUALIFY ROW_NUMBER() OVER (
        ORDER BY SNAPSHOT_AT DESC, SNAPSHOT_ID DESC
    ) = 1
)
SELECT
    L.SNAPSHOT_ID,
    L.SNAPSHOT_AT,
    COUNT(E.SNAPSHOT_ID) AS SNAPSHOT_EDGE_COUNT,
    COUNT_IF(E.SOURCE_OBJECT_DATABASE = 'RAW') AS SNAPSHOT_RAW_EDGE_COUNT,
    IFF(COUNT(E.SNAPSHOT_ID) > 0, 'PASS', 'FAIL') AS SNAPSHOT_STATUS
FROM LATEST_SNAPSHOT AS L
LEFT JOIN GOVERNANCE.CATALOG.LINEAGE_EDGE AS E
    ON E.SNAPSHOT_ID = L.SNAPSHOT_ID
GROUP BY L.SNAPSHOT_ID, L.SNAPSHOT_AT;

-- 8-10. Exactly two metadata-only external fallback endpoint rows.
WITH EXTERNAL_EDGE_COUNTS AS
(
    SELECT
        COUNT(*) AS EXTERNAL_EDGE_COUNT,
        COUNT_IF(
            SOURCE_SYSTEM = 'TALEND'
            AND SOURCE_OBJECT = 'LEGACY_TALEND_DEPOSIT_LOAD'
            AND SOURCE_OBJECT_TYPE = 'EXTERNAL_ETL_JOB'
            AND TARGET_SYSTEM = 'SNOWFLAKE'
            AND TARGET_OBJECT = 'RAW.BANKING.ACCOUNT_DAILY_BALANCE'
            AND TARGET_OBJECT_TYPE = 'TABLE'
            AND EDGE_TYPE = 'UPSTREAM_EXTERNAL'
        ) AS TALEND_ENDPOINT_ROW_COUNT,
        COUNT_IF(
            SOURCE_SYSTEM = 'SNOWFLAKE'
            AND SOURCE_OBJECT = 'ANALYTICS.MARTS.DEPOSITS_DAILY'
            AND SOURCE_OBJECT_TYPE = 'TABLE'
            AND TARGET_SYSTEM = 'POWER_BI'
            AND TARGET_OBJECT = 'POWER_BI_DEPOSITS_MODEL'
            AND TARGET_OBJECT_TYPE = 'EXTERNAL_BI_ENDPOINT'
            AND EDGE_TYPE = 'DOWNSTREAM_EXTERNAL'
        ) AS POWER_BI_ENDPOINT_ROW_COUNT,
        COUNT_IF(
            SOURCE_SYSTEM = 'TALEND'
            AND SOURCE_OBJECT = 'LEGACY_TALEND_DEPOSIT_LOAD'
            AND TARGET_OBJECT = 'RAW.BANKING.ACCOUNT_DAILY_BALANCE'
        ) AS TALEND_EDGE_COUNT,
        COUNT_IF(
            SOURCE_SYSTEM = 'SNOWFLAKE'
            AND SOURCE_OBJECT = 'ANALYTICS.MARTS.DEPOSITS_DAILY'
            AND TARGET_SYSTEM = 'POWER_BI'
            AND TARGET_OBJECT = 'POWER_BI_DEPOSITS_MODEL'
        ) AS POWER_BI_EDGE_COUNT
    FROM GOVERNANCE.CATALOG.LINEAGE_EDGE_EXTERNAL
)
SELECT
    EXTERNAL_EDGE_COUNT,
    TALEND_ENDPOINT_ROW_COUNT,
    POWER_BI_ENDPOINT_ROW_COUNT,
    TALEND_EDGE_COUNT,
    POWER_BI_EDGE_COUNT,
    IFF(
        EXTERNAL_EDGE_COUNT = 2
        AND TALEND_ENDPOINT_ROW_COUNT = 1
        AND POWER_BI_ENDPOINT_ROW_COUNT = 1,
        'PASS',
        'FAIL'
    ) AS EXTERNAL_METADATA_STATUS,
    'POWER_BI_DEPOSITS_MODEL and LEGACY_TALEND_DEPOSIT_LOAD are metadata strings only; no physical Talend or Power BI Snowflake objects are required.'
        AS EXTERNAL_RESOURCE_NOTE
FROM EXTERNAL_EDGE_COUNTS;

-- The external endpoints are separate from native Snowflake lineage.
SELECT
    'NATIVE SNOWFLAKE LINEAGE' AS LINEAGE_SECTION,
    'RAW -> STAGING -> ANALYTICS.MARTS.DEPOSITS_DAILY' AS REPRESENTATION
UNION ALL
SELECT
    'EXTERNAL FALLBACK METADATA',
    'TALEND endpoint -> RAW, and ANALYTICS.MARTS.DEPOSITS_DAILY -> POWER_BI endpoint';

-- 11. OBJECT_DEPENDENCIES evidence query. Account Usage can lag and may not
-- capture data-copy lineage; zero rows here is not a native lineage failure.
SELECT
    REFERENCED_DATABASE,
    REFERENCED_SCHEMA,
    REFERENCED_OBJECT_NAME,
    REFERENCING_DATABASE,
    REFERENCING_SCHEMA,
    REFERENCING_OBJECT_NAME,
    DEPENDENCY_TYPE
FROM SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES
WHERE REFERENCING_OBJECT_NAME = 'DEPOSITS_DAILY'
   OR REFERENCED_OBJECT_NAME IN
      (
          'ACCOUNT_DAILY_BALANCE',
          'STG_ACCOUNT_DAILY_BALANCE',
          'ACCOUNT',
          'STG_ACCOUNT'
      )
ORDER BY REFERENCED_OBJECT_NAME, REFERENCING_OBJECT_NAME
LIMIT 50;

-- 12. ACCESS_HISTORY evidence query. Account Usage can lag.
SELECT
    QUERY_START_TIME,
    USER_NAME,
    QUERY_ID,
    DIRECT_OBJECTS_ACCESSED,
    BASE_OBJECTS_ACCESSED,
    OBJECTS_MODIFIED
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD('DAY', -7, CURRENT_TIMESTAMP())
  AND
  (
      DIRECT_OBJECTS_ACCESSED::VARCHAR ILIKE '%DEPOSITS_DAILY%'
      OR BASE_OBJECTS_ACCESSED::VARCHAR ILIKE '%DEPOSITS_DAILY%'
      OR OBJECTS_MODIFIED::VARCHAR ILIKE '%DEPOSITS_DAILY%'
      OR DIRECT_OBJECTS_ACCESSED::VARCHAR ILIKE '%ACCOUNT_DAILY_BALANCE%'
      OR BASE_OBJECTS_ACCESSED::VARCHAR ILIKE '%ACCOUNT_DAILY_BALANCE%'
      OR OBJECTS_MODIFIED::VARCHAR ILIKE '%ACCOUNT_DAILY_BALANCE%'
  )
ORDER BY QUERY_START_TIME DESC
LIMIT 20;

-- 13-14. Concise evidence pack summary.
WITH TABLE_LINEAGE AS
(
    SELECT *
    FROM TABLE
    (
        SNOWFLAKE.CORE.GET_LINEAGE
        (
            'ANALYTICS.MARTS.DEPOSITS_DAILY',
            'TABLE',
            'UPSTREAM',
            5
        )
    )
),
COLUMN_LINEAGE AS
(
    SELECT *
    FROM TABLE
    (
        SNOWFLAKE.CORE.GET_LINEAGE
        (
            'ANALYTICS.MARTS.DEPOSITS_DAILY.CLOSING_BALANCE',
            'COLUMN',
            'UPSTREAM',
            5
        )
    )
),
EXTERNAL_EDGES AS
(
    SELECT
        COUNT(*) AS EXTERNAL_EDGE_COUNT,
        COUNT_IF(
            SOURCE_SYSTEM = 'TALEND'
            AND TARGET_SYSTEM = 'SNOWFLAKE'
            AND SOURCE_OBJECT_TYPE = 'EXTERNAL_ETL_JOB'
        ) AS TALEND_ENDPOINT_ROW_COUNT,
        COUNT_IF(
            SOURCE_SYSTEM = 'SNOWFLAKE'
            AND TARGET_SYSTEM = 'POWER_BI'
            AND TARGET_OBJECT_TYPE = 'EXTERNAL_BI_ENDPOINT'
            AND SOURCE_OBJECT = 'ANALYTICS.MARTS.DEPOSITS_DAILY'
        ) AS POWER_BI_ENDPOINT_ROW_COUNT
    FROM GOVERNANCE.CATALOG.LINEAGE_EDGE_EXTERNAL
),
SNAPSHOTS AS
(
    SELECT COUNT(*) AS SNAPSHOT_EDGE_COUNT
    FROM GOVERNANCE.CATALOG.LINEAGE_EDGE
),
SUMMARY AS
(
    SELECT
        COUNT(T.SOURCE_OBJECT_NAME) > 0 AS HAS_NATIVE_TABLE_LINEAGE,
        COUNT_IF(T.SOURCE_OBJECT_DATABASE = 'RAW') > 0 AS REACHES_RAW,
        COUNT_IF(C.SOURCE_OBJECT_DATABASE = 'RAW'
                 AND C.SOURCE_COLUMN_NAME = 'CLOSING_BALANCE') > 0
            AS HAS_WORKED_COLUMN_TRACE,
        MAX(E.EXTERNAL_EDGE_COUNT) = 2
            AND MAX(E.TALEND_ENDPOINT_ROW_COUNT) = 1
            AND MAX(E.POWER_BI_ENDPOINT_ROW_COUNT) = 1
            AS HAS_TWO_EXTERNAL_EDGES,
        MAX(S.SNAPSHOT_EDGE_COUNT) > 0 AS HAS_LINEAGE_SNAPSHOT
    FROM TABLE_LINEAGE AS T
    CROSS JOIN COLUMN_LINEAGE AS C
    CROSS JOIN EXTERNAL_EDGES AS E
    CROSS JOIN SNAPSHOTS AS S
)
SELECT
    HAS_NATIVE_TABLE_LINEAGE,
    REACHES_RAW,
    HAS_WORKED_COLUMN_TRACE,
    HAS_TWO_EXTERNAL_EDGES,
    HAS_LINEAGE_SNAPSHOT,
    IFF(
        HAS_NATIVE_TABLE_LINEAGE
        AND REACHES_RAW
        AND HAS_WORKED_COLUMN_TRACE
        AND HAS_TWO_EXTERNAL_EDGES
        AND HAS_LINEAGE_SNAPSHOT,
        'PASS',
        'FAIL'
    ) AS BLOCK_4_LINEAGE_STATUS
FROM SUMMARY;
