/*==============================================================================
 AVIDIA BANK - CERTIFICATION PERMISSIONS

 Purpose:
   Grant the minimum privileges needed to deploy and run the Block 5
   CERTIFY(object) procedure.
==============================================================================*/

USE ROLE SECURITYADMIN;

GRANT USAGE ON DATABASE GOVERNANCE TO ROLE DATA_GOVERNANCE_ADMIN;
GRANT USAGE ON SCHEMA GOVERNANCE.EVIDENCE TO ROLE DATA_GOVERNANCE_ADMIN;
GRANT CREATE TABLE ON SCHEMA GOVERNANCE.EVIDENCE TO ROLE DATA_GOVERNANCE_ADMIN;
GRANT CREATE PROCEDURE ON SCHEMA GOVERNANCE.EVIDENCE TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE ON SCHEMA GOVERNANCE.CATALOG TO ROLE DATA_GOVERNANCE_ADMIN;
GRANT USAGE ON SCHEMA GOVERNANCE.TAGS TO ROLE DATA_GOVERNANCE_ADMIN;
GRANT USAGE ON SCHEMA GOVERNANCE.DQ TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT SELECT ON TABLE GOVERNANCE.CATALOG.TAG_ASSIGNMENT TO ROLE DATA_GOVERNANCE_ADMIN;
GRANT SELECT ON TABLE GOVERNANCE.CATALOG.CDE_REGISTRY TO ROLE DATA_GOVERNANCE_ADMIN;
GRANT SELECT ON TABLE GOVERNANCE.DQ.DQ_RESULT TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE ON DATABASE ANALYTICS TO ROLE DATA_GOVERNANCE_ADMIN;
GRANT USAGE ON SCHEMA ANALYTICS.MARTS TO ROLE DATA_GOVERNANCE_ADMIN;
GRANT REFERENCES ON TABLE ANALYTICS.MARTS.DEPOSITS_DAILY TO ROLE DATA_GOVERNANCE_ADMIN;
GRANT REFERENCES ON TABLE ANALYTICS.MARTS.CUSTOMER_360 TO ROLE DATA_GOVERNANCE_ADMIN;
GRANT REFERENCES ON TABLE ANALYTICS.MARTS.LOAN_PORTFOLIO TO ROLE DATA_GOVERNANCE_ADMIN;

-- Prerequisite verified during inspection:
-- DATA_GOVERNANCE_ADMIN already has APPLY TAG on ACCOUNT in the current
-- environment. This script intentionally does not grant that broad privilege.

GRANT USAGE ON WAREHOUSE WH_GOVERNANCE_XS TO ROLE DATA_GOVERNANCE_ADMIN;

SHOW GRANTS TO ROLE DATA_GOVERNANCE_ADMIN;
