/*==============================================================================
 AVIDIA BANK - VALIDATE CERTIFICATION

 Purpose:
   Evidence queries for Block 5 CERTIFY(object).
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;

SHOW PROCEDURES LIKE 'CERTIFY' IN SCHEMA GOVERNANCE.EVIDENCE;
SHOW TABLES LIKE 'CERTIFICATION_LOG' IN SCHEMA GOVERNANCE.EVIDENCE;

-- Owner and steward evidence.
SELECT
    TAG_NAME,
    TAG_VALUE,
    LEVEL,
    APPLY_METHOD
FROM TABLE
(
    ANALYTICS.INFORMATION_SCHEMA.TAG_REFERENCES
    (
        'ANALYTICS.MARTS.DEPOSITS_DAILY',
        'TABLE'
    )
)
WHERE TAG_DATABASE = 'GOVERNANCE'
  AND TAG_SCHEMA = 'TAGS'
  AND TAG_NAME IN ('DATA_OWNER', 'DATA_STEWARD', 'CERTIFICATION')
ORDER BY TAG_NAME;

-- Description coverage evidence: expected 100%.
WITH OBJECT_DESCRIPTION AS
(
    SELECT COUNT_IF(COMMENT IS NOT NULL AND TRIM(COMMENT) <> '') AS TABLE_DESCRIPTION_COUNT
    FROM ANALYTICS.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'MARTS'
      AND TABLE_NAME = 'DEPOSITS_DAILY'
),
COLUMN_DESCRIPTION AS
(
    SELECT
        COUNT(*) AS TOTAL_COLUMNS,
        COUNT_IF(COMMENT IS NOT NULL AND TRIM(COMMENT) <> '') AS DESCRIBED_COLUMNS
    FROM ANALYTICS.INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'MARTS'
      AND TABLE_NAME = 'DEPOSITS_DAILY'
)
SELECT
    TABLE_DESCRIPTION_COUNT,
    TOTAL_COLUMNS,
    DESCRIBED_COLUMNS,
    ROUND(100.0 * DESCRIBED_COLUMNS / NULLIF(TOTAL_COLUMNS, 0), 2)
        AS DESCRIPTION_COVERAGE_PCT,
    IFF(
        TABLE_DESCRIPTION_COUNT = 1
        AND TOTAL_COLUMNS = DESCRIBED_COLUMNS,
        'PASS',
        'FAIL'
    ) AS DESCRIPTION_STATUS
FROM OBJECT_DESCRIPTION
CROSS JOIN COLUMN_DESCRIPTION;

-- CDE evidence for relevant DEPOSITS CDEs exposed by DEPOSITS_DAILY.
WITH REQUIRED_CDES AS
(
    SELECT DISTINCT
        R.COLUMN_NAME,
        R.CDE_TIER
    FROM GOVERNANCE.CATALOG.CDE_REGISTRY R
    INNER JOIN ANALYTICS.INFORMATION_SCHEMA.COLUMNS C
        ON C.COLUMN_NAME = R.COLUMN_NAME
       AND C.TABLE_SCHEMA = 'MARTS'
       AND C.TABLE_NAME = 'DEPOSITS_DAILY'
    WHERE R.ACTIVE_FLAG = TRUE
      AND R.DATA_DOMAIN = 'DEPOSITS'
),
ACTUAL_CDE_TAGS AS
(
    SELECT
        COLUMN_NAME,
        TAG_VALUE
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS
        (
            'ANALYTICS.MARTS.DEPOSITS_DAILY',
            'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CDE'
)
SELECT
    COUNT(*) AS REQUIRED_CDES,
    COUNT_IF(A.TAG_VALUE = R.CDE_TIER) AS MATCHED_CDE_TAGS,
    IFF(COUNT(*) > 0 AND COUNT_IF(A.TAG_VALUE = R.CDE_TIER) = COUNT(*), 'PASS', 'FAIL')
        AS CDE_STATUS
FROM REQUIRED_CDES R
LEFT JOIN ACTUAL_CDE_TAGS A
    ON A.COLUMN_NAME = R.COLUMN_NAME;

-- Classification and policy coverage evidence for DEPOSITS_DAILY.
WITH APPROVED_TARGETS AS
(
    SELECT COLUMN_NAME, TAG_VALUE
    FROM GOVERNANCE.CATALOG.TAG_ASSIGNMENT
    WHERE DATABASE_NAME = 'ANALYTICS'
      AND SCHEMA_NAME = 'MARTS'
      AND OBJECT_NAME = 'DEPOSITS_DAILY'
      AND TAG_NAME = 'CLASSIFICATION'
      AND SOURCE_TYPE = 'CLASSIFICATION_REVIEW'
      AND ACTIVE_FLAG = TRUE
),
ACTUAL_TAGS AS
(
    SELECT COLUMN_NAME, TAG_VALUE
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS
        (
            'ANALYTICS.MARTS.DEPOSITS_DAILY',
            'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'
),
POLICY_REFS AS
(
    SELECT REF_COLUMN_NAME AS COLUMN_NAME, POLICY_STATUS
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.POLICY_REFERENCES
        (
            REF_ENTITY_NAME => 'ANALYTICS.MARTS.DEPOSITS_DAILY',
            REF_ENTITY_DOMAIN => 'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'
)
SELECT
    COUNT(*) AS CONFIRMED_CLASSIFIED_COLUMNS,
    COUNT_IF(A.TAG_VALUE = T.TAG_VALUE) AS MATCHING_CLASSIFICATION_TAGS,
    COUNT_IF(P.POLICY_STATUS = 'ACTIVE') AS ACTIVE_POLICY_REFERENCES,
    COUNT_IF(
        A.COLUMN_NAME IS NULL
        OR A.TAG_VALUE <> T.TAG_VALUE
        OR P.COLUMN_NAME IS NULL
        OR P.POLICY_STATUS <> 'ACTIVE'
    ) AS POLICY_GAP_COUNT,
    IFF(POLICY_GAP_COUNT = 0, 'PASS', 'FAIL') AS POLICY_STATUS
FROM APPROVED_TARGETS T
LEFT JOIN ACTUAL_TAGS A
    ON A.COLUMN_NAME = T.COLUMN_NAME
LEFT JOIN POLICY_REFS P
    ON P.COLUMN_NAME = T.COLUMN_NAME
   AND P.POLICY_STATUS = 'ACTIVE';

-- Latest DQ run evidence: expected six dimensions and six PASS.
WITH LATEST_DQ AS
(
    SELECT *
    FROM GOVERNANCE.DQ.DQ_RESULT
    WHERE OBJECT_FQN = 'ANALYTICS.MARTS.DEPOSITS_DAILY'
    QUALIFY DENSE_RANK() OVER
    (
        ORDER BY MEASURED_AT DESC, RUN_ID DESC
    ) = 1
)
SELECT
    COUNT(*) AS TOTAL_CHECKS,
    COUNT(DISTINCT QUALITY_DIMENSION) AS DISTINCT_DIMENSIONS,
    COUNT_IF(STATUS = 'PASS') AS PASSED_CHECKS,
    COUNT_IF(STATUS = 'FAIL') AS FAILED_CHECKS,
    LISTAGG(DISTINCT QUALITY_DIMENSION, ', ')
        WITHIN GROUP (ORDER BY QUALITY_DIMENSION) AS DIMENSIONS,
    IFF(
        TOTAL_CHECKS = 6
        AND DISTINCT_DIMENSIONS = 6
        AND PASSED_CHECKS = 6
        AND FAILED_CHECKS = 0,
        'PASS',
        'FAIL'
    ) AS DQ_STATUS
FROM LATEST_DQ;

-- Certification and refusal evidence.
SELECT
    OBJECT_FQN,
    OUTCOME,
    OWNER_CHECK,
    STEWARD_CHECK,
    DESCRIPTION_CHECK,
    CDE_CHECK,
    CLASSIFICATION_CHECK,
    POLICY_CHECK,
    DQ_CHECK,
    FAILURE_REASONS,
    CERTIFIED_AT
FROM GOVERNANCE.EVIDENCE.CERTIFICATION_LOG
QUALIFY ROW_NUMBER() OVER
(
    PARTITION BY OBJECT_FQN
    ORDER BY REQUESTED_AT DESC, CERTIFICATION_RUN_ID DESC
) = 1
ORDER BY OBJECT_FQN;

-- Refused object should not have CERTIFICATION = CERTIFIED.
SELECT
    COALESCE(MAX(TAG_VALUE), 'NO_CERTIFICATION_TAG') AS CUSTOMER_360_CERTIFICATION
FROM TABLE
(
    ANALYTICS.INFORMATION_SCHEMA.TAG_REFERENCES
    (
        'ANALYTICS.MARTS.CUSTOMER_360',
        'TABLE'
    )
)
WHERE TAG_DATABASE = 'GOVERNANCE'
  AND TAG_SCHEMA = 'TAGS'
  AND TAG_NAME = 'CERTIFICATION';

-- Concise interview/evidence summary.
SELECT
    OBJECT_FQN,
    OUTCOME,
    IFF(
        OUTCOME = 'CERTIFIED',
        'NONE',
        RTRIM(
            IFF(NOT OWNER_CHECK, 'OWNER, ', '')
            || IFF(NOT STEWARD_CHECK, 'STEWARD, ', '')
            || IFF(NOT DESCRIPTION_CHECK, 'DESCRIPTION, ', '')
            || IFF(NOT CDE_CHECK, 'CDE, ', '')
            || IFF(NOT CLASSIFICATION_CHECK, 'CLASSIFICATION, ', '')
            || IFF(NOT POLICY_CHECK, 'POLICY, ', '')
            || IFF(NOT DQ_CHECK, 'DQ, ', ''),
            ', '
        )
    ) AS FAILED_GATES
FROM GOVERNANCE.EVIDENCE.CERTIFICATION_LOG
QUALIFY ROW_NUMBER() OVER
(
    PARTITION BY OBJECT_FQN
    ORDER BY REQUESTED_AT DESC, CERTIFICATION_RUN_ID DESC
) = 1
ORDER BY OBJECT_FQN;
