--First validate that the procedure actually exists

SHOW USER PROCEDURES LIKE 'CERTIFY'
IN SCHEMA GOVERNANCE.EVIDENCE;


DESC PROCEDURE GOVERNANCE.EVIDENCE.CERTIFY(VARCHAR);

--Run the successful certification manually

CALL GOVERNANCE.EVIDENCE.CERTIFY(
    'ANALYTICS.MARTS.DEPOSITS_DAILY'
);

--Verify that the CERTIFICATION tag really got applied

SELECT SYSTEM$GET_TAG(
    'GOVERNANCE.TAGS.CERTIFICATION',
    'ANALYTICS.MARTS.DEPOSITS_DAILY',
    'TABLE'
) AS CERTIFICATION_STATUS;



-- Validate the audit log

SELECT
    CERTIFICATION_RUN_ID,
    OBJECT_FQN,
    REQUESTED_AT,
    REQUESTED_BY,

    OWNER_CHECK,
    STEWARD_CHECK,
    DESCRIPTION_CHECK,
    CDE_CHECK,
    CLASSIFICATION_CHECK,
    POLICY_CHECK,
    DQ_CHECK,

    OUTCOME,
    FAILURE_REASONS,
    CERTIFIED_AT
FROM GOVERNANCE.EVIDENCE.CERTIFICATION_LOG
ORDER BY REQUESTED_AT DESC;