/*==============================================================================
 AVIDIA BANK - CLASSIFICATION PHASE PERMISSIONS
 File: classification/01_permissions.sql

 Purpose:
   Minimum practical privileges for the existing DATA_GOVERNANCE_ADMIN role
   to implement Block 2 classification on ANALYTICS.STAGING.

 Notes:
   - Classification discovery runs on STAGING.
   - The profile may auto-apply Snowflake system classification tags.
   - The custom governance tag GOVERNANCE.TAGS.CLASSIFICATION is set only
     after steward approval through the existing TAG_ASSIGNMENT framework.
   - No business-consumer role is granted access to STAGING here.
==============================================================================*/

USE ROLE SECURITYADMIN;

-- Snowflake classification administration.
GRANT DATABASE ROLE SNOWFLAKE.CLASSIFICATION_ADMIN
TO ROLE DATA_GOVERNANCE_ADMIN;

-- Parent-object access.
GRANT USAGE ON DATABASE GOVERNANCE
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE ON DATABASE ANALYTICS
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE ON SCHEMA ANALYTICS.STAGING
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE ON WAREHOUSE WH_GOVERNANCE_XS
TO ROLE DATA_GOVERNANCE_ADMIN;

-- Create Snowflake classification objects in the governed catalog schema.
GRANT CREATE SNOWFLAKE.DATA_PRIVACY.CLASSIFICATION_PROFILE
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT CREATE SNOWFLAKE.DATA_PRIVACY.CUSTOM_CLASSIFIER
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

-- Associate an automatic classification profile with STAGING.
GRANT EXECUTE AUTO CLASSIFICATION
ON SCHEMA ANALYTICS.STAGING
TO ROLE DATA_GOVERNANCE_ADMIN;

-- Required by Snowflake automatic classification when auto-tagging is enabled.
GRANT APPLY TAG
ON ACCOUNT
TO ROLE DATA_GOVERNANCE_ADMIN;

-- Read STAGING for validation / explicit test classification.
GRANT SELECT
ON ALL TABLES IN SCHEMA ANALYTICS.STAGING
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA ANALYTICS.STAGING
TO ROLE DATA_GOVERNANCE_ADMIN;

-- Persist candidate results, sealed-list comparison, review queue and procedures.
GRANT CREATE TABLE
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT CREATE PROCEDURE
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT CREATE STAGE
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

-- Existing metadata control-plane tables used by the approval/sync workflow.
GRANT SELECT, INSERT, UPDATE
ON TABLE GOVERNANCE.CATALOG.TAG_ASSIGNMENT
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT SELECT
ON TABLE GOVERNANCE.CATALOG.OBJECT_CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT SELECT
ON TABLE GOVERNANCE.CATALOG.COLUMN_CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

-- Verification.
SHOW GRANTS TO ROLE DATA_GOVERNANCE_ADMIN;
