/*==============================================================================
 AVIDIA BANK - BLOCK 2 CLASSIFICATION SUPPORT TABLES

 Purpose:
   Create the minimal governed tables required for classification evidence,
   sealed-list evaluation and steward review.
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE FILE FORMAT IF NOT EXISTS GOVERNANCE.CATALOG.JSON_FILE_FORMAT
    TYPE = JSON
    STRIP_OUTER_ARRAY = FALSE;

CREATE STAGE IF NOT EXISTS GOVERNANCE.CATALOG.CLASSIFICATION_FILE_STAGE
    FILE_FORMAT = GOVERNANCE.CATALOG.JSON_FILE_FORMAT
    COMMENT = 'Internal stage for sealed sensitive-column JSON used by Block 2 classification.';

CREATE TABLE IF NOT EXISTS GOVERNANCE.CATALOG.SEALED_SENSITIVE_COLUMN
(
    RAW_DATABASE_NAME          VARCHAR(255) DEFAULT 'RAW',
    RAW_SCHEMA_NAME            VARCHAR(255) DEFAULT 'BANKING',
    RAW_TABLE_NAME             VARCHAR(255) NOT NULL,
    RAW_COLUMN_NAME            VARCHAR(255) NOT NULL,

    STAGING_DATABASE_NAME      VARCHAR(255) DEFAULT 'ANALYTICS',
    STAGING_SCHEMA_NAME        VARCHAR(255) DEFAULT 'STAGING',
    STAGING_TABLE_NAME         VARCHAR(255) NOT NULL,
    STAGING_COLUMN_NAME        VARCHAR(255) NOT NULL,

    EXPECTED_SENSITIVE         BOOLEAN,
    EXPECTED_SENSITIVE_CONTENT VARCHAR(255),
    DELIBERATELY_MISLABELED    BOOLEAN,

    FULLY_QUALIFIED_NAME       VARCHAR(500),
    LOADED_AT                  TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Committed sealed sensitive-column truth set loaded from data/sealed_sensitive_columns.json.';

CREATE TABLE IF NOT EXISTS GOVERNANCE.CATALOG.CLASSIFICATION_RUN_RESULT
(
    DATABASE_NAME              VARCHAR(255) NOT NULL,
    SCHEMA_NAME                VARCHAR(255) NOT NULL,
    TABLE_NAME                 VARCHAR(255) NOT NULL,
    CLASSIFICATION_PROFILE     VARCHAR(500),
    RUN_RESULT                 VARIANT,
    CLASSIFIED_AT              TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Raw JSON output from deterministic SYSTEM$CLASSIFY runs on ANALYTICS.STAGING.';

CREATE TABLE IF NOT EXISTS GOVERNANCE.CATALOG.CLASSIFICATION_CANDIDATE
(
    DATABASE_NAME              VARCHAR(255) NOT NULL,
    SCHEMA_NAME                VARCHAR(255) NOT NULL,
    TABLE_NAME                 VARCHAR(255) NOT NULL,
    COLUMN_NAME                VARCHAR(255) NOT NULL,

    SEMANTIC_CATEGORY          VARCHAR(255),
    PRIVACY_CATEGORY           VARCHAR(255),
    CONFIDENCE                 VARCHAR(50),
    COVERAGE                   FLOAT,
    VALID_VALUE_RATIO          FLOAT,

    CLASSIFIER_NAME            VARCHAR(500),
    DETECTION_SOURCE           VARCHAR(255),
    CLASSIFICATION_PROFILE     VARCHAR(500),
    DETECTED_AT                TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),

    ACTIVE_FLAG                BOOLEAN DEFAULT TRUE,
    UPDATED_AT                 TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Machine-detected classification candidates. These are evidence only, not confirmed governance decisions.';

CREATE TABLE IF NOT EXISTS GOVERNANCE.CATALOG.CLASSIFICATION_REVIEW_QUEUE
(
    REVIEW_ID                  NUMBER AUTOINCREMENT START 1 INCREMENT 1,

    DATABASE_NAME              VARCHAR(255) NOT NULL,
    SCHEMA_NAME                VARCHAR(255) NOT NULL,
    TABLE_NAME                 VARCHAR(255) NOT NULL,
    COLUMN_NAME                VARCHAR(255) NOT NULL,

    SEMANTIC_CATEGORY          VARCHAR(255),
    PRIVACY_CATEGORY           VARCHAR(255),
    CONFIDENCE                 VARCHAR(50),
    COVERAGE                   FLOAT,
    DETECTION_SOURCE           VARCHAR(255),

    PROPOSED_CLASSIFICATION    VARCHAR(50),
    APPROVED_CLASSIFICATION    VARCHAR(50),

    REVIEW_STATUS              VARCHAR(50) DEFAULT 'PENDING',
    REVIEWED_BY                VARCHAR(255),
    REVIEWED_AT                TIMESTAMP_LTZ,
    REVIEW_COMMENT             VARCHAR(5000),

    CREATED_AT                 TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT                 TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT CK_CLASSIFICATION_REVIEW_STATUS
        CHECK (REVIEW_STATUS IN ('PENDING', 'APPROVED', 'REJECTED')),

    CONSTRAINT CK_CLASSIFICATION_REVIEW_VALUE
        CHECK (
            APPROVED_CLASSIFICATION IS NULL
            OR APPROVED_CLASSIFICATION IN
                ('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED')
        )
)
COMMENT = 'Steward review queue for machine-detected classification candidates.';

SHOW TABLES LIKE '%CLASSIFICATION%' IN SCHEMA GOVERNANCE.CATALOG;
SHOW TABLES LIKE 'SEALED_SENSITIVE_COLUMN' IN SCHEMA GOVERNANCE.CATALOG;
