/*==============================================================================
 AVIDIA BANK - RUN STAGING CLASSIFICATION

 Purpose:
   Deterministically run SYSTEM$CLASSIFY against existing ANALYTICS.STAGING
   tables using the governed classification profile.

 Scope:
   STAGING only. This script does not classify RAW or MARTS and does not set
   GOVERNANCE.TAGS.CLASSIFICATION.
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

TRUNCATE TABLE GOVERNANCE.CATALOG.CLASSIFICATION_RUN_RESULT;

CALL SYSTEM$CLASSIFY(
    'ANALYTICS.STAGING.STG_CUSTOMER',
    'GOVERNANCE.CATALOG.STAGING_CLASSIFICATION_PROFILE'
);

INSERT INTO GOVERNANCE.CATALOG.CLASSIFICATION_RUN_RESULT
(
    DATABASE_NAME,
    SCHEMA_NAME,
    TABLE_NAME,
    CLASSIFICATION_PROFILE,
    RUN_RESULT
)
SELECT
    'ANALYTICS',
    'STAGING',
    'STG_CUSTOMER',
    'GOVERNANCE.CATALOG.STAGING_CLASSIFICATION_PROFILE',
    $1::VARIANT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

CALL SYSTEM$CLASSIFY(
    'ANALYTICS.STAGING.STG_ACCOUNT',
    'GOVERNANCE.CATALOG.STAGING_CLASSIFICATION_PROFILE'
);

INSERT INTO GOVERNANCE.CATALOG.CLASSIFICATION_RUN_RESULT
(
    DATABASE_NAME,
    SCHEMA_NAME,
    TABLE_NAME,
    CLASSIFICATION_PROFILE,
    RUN_RESULT
)
SELECT
    'ANALYTICS',
    'STAGING',
    'STG_ACCOUNT',
    'GOVERNANCE.CATALOG.STAGING_CLASSIFICATION_PROFILE',
    $1::VARIANT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

CALL SYSTEM$CLASSIFY(
    'ANALYTICS.STAGING.STG_TRANSACTIONS',
    'GOVERNANCE.CATALOG.STAGING_CLASSIFICATION_PROFILE'
);

INSERT INTO GOVERNANCE.CATALOG.CLASSIFICATION_RUN_RESULT
(
    DATABASE_NAME,
    SCHEMA_NAME,
    TABLE_NAME,
    CLASSIFICATION_PROFILE,
    RUN_RESULT
)
SELECT
    'ANALYTICS',
    'STAGING',
    'STG_TRANSACTIONS',
    'GOVERNANCE.CATALOG.STAGING_CLASSIFICATION_PROFILE',
    $1::VARIANT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

CALL SYSTEM$CLASSIFY(
    'ANALYTICS.STAGING.STG_CARD',
    'GOVERNANCE.CATALOG.STAGING_CLASSIFICATION_PROFILE'
);

INSERT INTO GOVERNANCE.CATALOG.CLASSIFICATION_RUN_RESULT
(
    DATABASE_NAME,
    SCHEMA_NAME,
    TABLE_NAME,
    CLASSIFICATION_PROFILE,
    RUN_RESULT
)
SELECT
    'ANALYTICS',
    'STAGING',
    'STG_CARD',
    'GOVERNANCE.CATALOG.STAGING_CLASSIFICATION_PROFILE',
    $1::VARIANT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SELECT
    DATABASE_NAME,
    SCHEMA_NAME,
    TABLE_NAME,
    CLASSIFIED_AT
FROM GOVERNANCE.CATALOG.CLASSIFICATION_RUN_RESULT
ORDER BY TABLE_NAME;
