/*==============================================================================
 AVIDIA BANK - CLASSIFICATION PRECISION / RECALL

 Purpose:
   Compare Snowflake machine-detected candidates against the sealed sensitive
   column truth set.

 Notes:
   - The sealed list is evaluation truth only.
   - It does not auto-approve governance classification decisions.
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

WITH SEALED AS
(
    SELECT DISTINCT
        STAGING_DATABASE_NAME AS DATABASE_NAME,
        STAGING_SCHEMA_NAME AS SCHEMA_NAME,
        STAGING_TABLE_NAME AS TABLE_NAME,
        STAGING_COLUMN_NAME AS COLUMN_NAME,
        EXPECTED_SENSITIVE_CONTENT,
        DELIBERATELY_MISLABELED
    FROM GOVERNANCE.CATALOG.SEALED_SENSITIVE_COLUMN
    WHERE EXPECTED_SENSITIVE = TRUE
),
CANDIDATE AS
(
    SELECT DISTINCT
        DATABASE_NAME,
        SCHEMA_NAME,
        TABLE_NAME,
        COLUMN_NAME,
        SEMANTIC_CATEGORY,
        PRIVACY_CATEGORY
    FROM GOVERNANCE.CATALOG.CLASSIFICATION_CANDIDATE
    WHERE ACTIVE_FLAG = TRUE
),
LABELED AS
(
    SELECT
        'TRUE_POSITIVE' AS RESULT_TYPE,
        C.DATABASE_NAME,
        C.SCHEMA_NAME,
        C.TABLE_NAME,
        C.COLUMN_NAME,
        C.SEMANTIC_CATEGORY,
        C.PRIVACY_CATEGORY,
        S.EXPECTED_SENSITIVE_CONTENT,
        S.DELIBERATELY_MISLABELED,
        NULL AS MISS_EXPLANATION
    FROM CANDIDATE C
    INNER JOIN SEALED S
        ON S.DATABASE_NAME = C.DATABASE_NAME
       AND S.SCHEMA_NAME = C.SCHEMA_NAME
       AND S.TABLE_NAME = C.TABLE_NAME
       AND S.COLUMN_NAME = C.COLUMN_NAME

    UNION ALL

    SELECT
        'FALSE_POSITIVE',
        C.DATABASE_NAME,
        C.SCHEMA_NAME,
        C.TABLE_NAME,
        C.COLUMN_NAME,
        C.SEMANTIC_CATEGORY,
        C.PRIVACY_CATEGORY,
        NULL,
        NULL,
        'Candidate was not present in sealed sensitive-column truth set.'
    FROM CANDIDATE C
    LEFT JOIN SEALED S
        ON S.DATABASE_NAME = C.DATABASE_NAME
       AND S.SCHEMA_NAME = C.SCHEMA_NAME
       AND S.TABLE_NAME = C.TABLE_NAME
       AND S.COLUMN_NAME = C.COLUMN_NAME
    WHERE S.COLUMN_NAME IS NULL

    UNION ALL

    SELECT
        'FALSE_NEGATIVE',
        S.DATABASE_NAME,
        S.SCHEMA_NAME,
        S.TABLE_NAME,
        S.COLUMN_NAME,
        NULL,
        NULL,
        S.EXPECTED_SENSITIVE_CONTENT,
        S.DELIBERATELY_MISLABELED,
        CASE
            WHEN S.DELIBERATELY_MISLABELED
                THEN 'Sensitive values are in innocently named columns; classifier may miss without content-based detection.'
            ELSE 'Expected sensitive column was not captured as a candidate.'
        END
    FROM SEALED S
    LEFT JOIN CANDIDATE C
        ON C.DATABASE_NAME = S.DATABASE_NAME
       AND C.SCHEMA_NAME = S.SCHEMA_NAME
       AND C.TABLE_NAME = S.TABLE_NAME
       AND C.COLUMN_NAME = S.COLUMN_NAME
    WHERE C.COLUMN_NAME IS NULL
),
COUNTS AS
(
    SELECT
        COUNT_IF(RESULT_TYPE = 'TRUE_POSITIVE') AS TRUE_POSITIVE,
        COUNT_IF(RESULT_TYPE = 'FALSE_POSITIVE') AS FALSE_POSITIVE,
        COUNT_IF(RESULT_TYPE = 'FALSE_NEGATIVE') AS FALSE_NEGATIVE
    FROM LABELED
)
SELECT
    TRUE_POSITIVE,
    FALSE_POSITIVE,
    FALSE_NEGATIVE,
    TRUE_POSITIVE / NULLIF(TRUE_POSITIVE + FALSE_POSITIVE, 0)
        AS PRECISION,
    TRUE_POSITIVE / NULLIF(TRUE_POSITIVE + FALSE_NEGATIVE, 0)
        AS RECALL
FROM COUNTS;

WITH SEALED AS
(
    SELECT DISTINCT
        STAGING_DATABASE_NAME AS DATABASE_NAME,
        STAGING_SCHEMA_NAME AS SCHEMA_NAME,
        STAGING_TABLE_NAME AS TABLE_NAME,
        STAGING_COLUMN_NAME AS COLUMN_NAME,
        EXPECTED_SENSITIVE_CONTENT,
        DELIBERATELY_MISLABELED
    FROM GOVERNANCE.CATALOG.SEALED_SENSITIVE_COLUMN
    WHERE EXPECTED_SENSITIVE = TRUE
),
CANDIDATE AS
(
    SELECT DISTINCT
        DATABASE_NAME,
        SCHEMA_NAME,
        TABLE_NAME,
        COLUMN_NAME,
        SEMANTIC_CATEGORY,
        PRIVACY_CATEGORY
    FROM GOVERNANCE.CATALOG.CLASSIFICATION_CANDIDATE
    WHERE ACTIVE_FLAG = TRUE
)
SELECT
    'FALSE_POSITIVE' AS RESULT_TYPE,
    C.DATABASE_NAME,
    C.SCHEMA_NAME,
    C.TABLE_NAME,
    C.COLUMN_NAME,
    C.SEMANTIC_CATEGORY,
    C.PRIVACY_CATEGORY,
    'Candidate was not present in sealed sensitive-column truth set.'
        AS MISS_EXPLANATION
FROM CANDIDATE C
LEFT JOIN SEALED S
    ON S.DATABASE_NAME = C.DATABASE_NAME
   AND S.SCHEMA_NAME = C.SCHEMA_NAME
   AND S.TABLE_NAME = C.TABLE_NAME
   AND S.COLUMN_NAME = C.COLUMN_NAME
WHERE S.COLUMN_NAME IS NULL

UNION ALL

SELECT
    'FALSE_NEGATIVE',
    S.DATABASE_NAME,
    S.SCHEMA_NAME,
    S.TABLE_NAME,
    S.COLUMN_NAME,
    NULL,
    NULL,
    CASE
        WHEN S.DELIBERATELY_MISLABELED
            THEN 'Sensitive values are in innocently named columns; classifier may miss without content-based detection.'
        ELSE 'Expected sensitive column was not captured as a candidate.'
    END
FROM SEALED S
LEFT JOIN CANDIDATE C
    ON C.DATABASE_NAME = S.DATABASE_NAME
   AND C.SCHEMA_NAME = S.SCHEMA_NAME
   AND C.TABLE_NAME = S.TABLE_NAME
   AND C.COLUMN_NAME = S.COLUMN_NAME
WHERE C.COLUMN_NAME IS NULL
ORDER BY
    RESULT_TYPE,
    TABLE_NAME,
    COLUMN_NAME;
