/*==============================================================================
 AVIDIA BANK - CLASSIFICATION REVIEW PROCEDURES

 Purpose:
   Create procedures for steward approval/rejection of machine-detected
   classification candidates.

 Design:
   - APPROVE creates desired-state CLASSIFICATION rows in TAG_ASSIGNMENT.
   - REJECT records governance decision only.
   - Neither procedure applies masking policies or tags directly.
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE OR REPLACE PROCEDURE GOVERNANCE.CATALOG.APPROVE_CLASSIFICATION
(
    P_REVIEW_ID NUMBER,
    P_CLASSIFICATION VARCHAR,
    P_REVIEW_COMMENT VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_PENDING_COUNT NUMBER DEFAULT 0;
    V_CLASSIFICATION VARCHAR DEFAULT UPPER(P_CLASSIFICATION);
BEGIN
    IF (V_CLASSIFICATION NOT IN ('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED')) THEN
        RETURN 'Invalid classification value. Use PUBLIC, INTERNAL, CONFIDENTIAL or RESTRICTED.';
    END IF;

    SELECT COUNT(*)
      INTO :V_PENDING_COUNT
    FROM GOVERNANCE.CATALOG.CLASSIFICATION_REVIEW_QUEUE
    WHERE REVIEW_ID = :P_REVIEW_ID
      AND REVIEW_STATUS = 'PENDING';

    IF (V_PENDING_COUNT = 0) THEN
        RETURN 'No pending review row found for REVIEW_ID=' || P_REVIEW_ID || '.';
    END IF;

    UPDATE GOVERNANCE.CATALOG.CLASSIFICATION_REVIEW_QUEUE
       SET REVIEW_STATUS = 'APPROVED',
           APPROVED_CLASSIFICATION = :V_CLASSIFICATION,
           REVIEWED_BY = CURRENT_USER(),
           REVIEWED_AT = CURRENT_TIMESTAMP(),
           REVIEW_COMMENT = :P_REVIEW_COMMENT,
           UPDATED_AT = CURRENT_TIMESTAMP()
     WHERE REVIEW_ID = :P_REVIEW_ID
       AND REVIEW_STATUS = 'PENDING';

    MERGE INTO GOVERNANCE.CATALOG.TAG_ASSIGNMENT T
    USING
    (
        SELECT
            DATABASE_NAME,
            SCHEMA_NAME,
            TABLE_NAME AS OBJECT_NAME,
            COLUMN_NAME,
            'COLUMN' AS OBJECT_LEVEL,
            'TABLE' AS OBJECT_TYPE,
            'CLASSIFICATION' AS TAG_NAME,
            :V_CLASSIFICATION AS TAG_VALUE,
            'CLASSIFICATION_REVIEW' AS SOURCE_TYPE,
            'REVIEW_ID=' || REVIEW_ID || ':STAGING' AS SOURCE_REFERENCE,
            'Steward-approved classification from CLASSIFICATION_REVIEW_QUEUE'
                AS ASSIGNMENT_REASON,
            200 AS APPLY_ORDER
        FROM GOVERNANCE.CATALOG.CLASSIFICATION_REVIEW_QUEUE
        WHERE REVIEW_ID = :P_REVIEW_ID
    ) S
    ON  T.DATABASE_NAME = S.DATABASE_NAME
    AND T.SCHEMA_NAME = S.SCHEMA_NAME
    AND T.OBJECT_NAME = S.OBJECT_NAME
    AND T.COLUMN_NAME = S.COLUMN_NAME
    AND T.OBJECT_LEVEL = S.OBJECT_LEVEL
    AND T.TAG_NAME = S.TAG_NAME
    WHEN MATCHED THEN UPDATE SET
        TAG_VALUE = S.TAG_VALUE,
        OBJECT_TYPE = S.OBJECT_TYPE,
        SOURCE_TYPE = S.SOURCE_TYPE,
        SOURCE_REFERENCE = S.SOURCE_REFERENCE,
        ASSIGNMENT_REASON = S.ASSIGNMENT_REASON,
        APPLY_ORDER = S.APPLY_ORDER,
        ACTIVE_FLAG = TRUE,
        UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT
    (
        DATABASE_NAME,
        SCHEMA_NAME,
        OBJECT_NAME,
        COLUMN_NAME,
        OBJECT_LEVEL,
        OBJECT_TYPE,
        TAG_NAME,
        TAG_VALUE,
        SOURCE_TYPE,
        SOURCE_REFERENCE,
        ASSIGNMENT_REASON,
        APPLY_ORDER,
        ACTIVE_FLAG
    )
    VALUES
    (
        S.DATABASE_NAME,
        S.SCHEMA_NAME,
        S.OBJECT_NAME,
        S.COLUMN_NAME,
        S.OBJECT_LEVEL,
        S.OBJECT_TYPE,
        S.TAG_NAME,
        S.TAG_VALUE,
        S.SOURCE_TYPE,
        S.SOURCE_REFERENCE,
        S.ASSIGNMENT_REASON,
        S.APPLY_ORDER,
        TRUE
    );

    RETURN 'Approved REVIEW_ID=' || P_REVIEW_ID || ' as ' || V_CLASSIFICATION || '.';
END;
$$;

CREATE OR REPLACE PROCEDURE GOVERNANCE.CATALOG.REJECT_CLASSIFICATION
(
    P_REVIEW_ID NUMBER,
    P_REJECT_REASON VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_PENDING_COUNT NUMBER DEFAULT 0;
BEGIN
    SELECT COUNT(*)
      INTO :V_PENDING_COUNT
    FROM GOVERNANCE.CATALOG.CLASSIFICATION_REVIEW_QUEUE
    WHERE REVIEW_ID = :P_REVIEW_ID
      AND REVIEW_STATUS = 'PENDING';

    IF (V_PENDING_COUNT = 0) THEN
        RETURN 'No pending review row found for REVIEW_ID=' || P_REVIEW_ID || '.';
    END IF;

    UPDATE GOVERNANCE.CATALOG.CLASSIFICATION_REVIEW_QUEUE
       SET REVIEW_STATUS = 'REJECTED',
           REVIEWED_BY = CURRENT_USER(),
           REVIEWED_AT = CURRENT_TIMESTAMP(),
           REVIEW_COMMENT = :P_REJECT_REASON,
           UPDATED_AT = CURRENT_TIMESTAMP()
     WHERE REVIEW_ID = :P_REVIEW_ID
       AND REVIEW_STATUS = 'PENDING';

    RETURN 'Rejected REVIEW_ID=' || P_REVIEW_ID || '.';
END;
$$;

SHOW PROCEDURES LIKE '%CLASSIFICATION%' IN SCHEMA GOVERNANCE.CATALOG;
