/*==============================================================================
 AVIDIA BANK - SYNC CONFIRMED CLASSIFICATION TAGS

 Purpose:
   Propagate steward-approved STAGING classification decisions to matching RAW
   and MART columns using GOVERNANCE.CATALOG.TAG_ASSIGNMENT.

 Scope:
   - STAGING receives the approved decision from APPROVE_CLASSIFICATION.
   - RAW receives matching source-column decisions.
   - MART receives decisions only where the sensitive field is actually exposed.
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

MERGE INTO GOVERNANCE.CATALOG.TAG_ASSIGNMENT T
USING
(
    WITH APPROVED AS
    (
        SELECT
            REVIEW_ID,
            DATABASE_NAME AS STAGING_DATABASE_NAME,
            SCHEMA_NAME AS STAGING_SCHEMA_NAME,
            TABLE_NAME AS STAGING_TABLE_NAME,
            COLUMN_NAME AS STAGING_COLUMN_NAME,
            APPROVED_CLASSIFICATION
        FROM GOVERNANCE.CATALOG.CLASSIFICATION_REVIEW_QUEUE
        WHERE REVIEW_STATUS = 'APPROVED'
          AND APPROVED_CLASSIFICATION IS NOT NULL
    ),
    COLUMN_MAP AS
    (
        SELECT * FROM VALUES
            ('STG_CUSTOMER', 'TAX_ID',        'RAW', 'BANKING', 'CUSTOMER',     'TAX_ID',        'ANALYTICS', 'MARTS', 'CUSTOMER_360',  'TAX_ID'),
            ('STG_CUSTOMER', 'DATE_OF_BIRTH', 'RAW', 'BANKING', 'CUSTOMER',     'DATE_OF_BIRTH', 'ANALYTICS', 'MARTS', 'CUSTOMER_360',  'DATE_OF_BIRTH'),
            ('STG_CUSTOMER', 'EMAIL',         'RAW', 'BANKING', 'CUSTOMER',     'EMAIL',         'ANALYTICS', 'MARTS', 'CUSTOMER_360',  'EMAIL'),
            ('STG_CUSTOMER', 'PHONE',         'RAW', 'BANKING', 'CUSTOMER',     'PHONE',         'ANALYTICS', 'MARTS', 'CUSTOMER_360',  'PHONE'),
            ('STG_CUSTOMER', 'CUST_REF',      'RAW', 'BANKING', 'CUSTOMER',     'CUST_REF',      'ANALYTICS', 'MARTS', 'CUSTOMER_360',  'CUST_REF'),
            ('STG_CUSTOMER', 'NOTES',         'RAW', 'BANKING', 'CUSTOMER',     'NOTES',         'ANALYTICS', 'MARTS', 'CUSTOMER_360',  'NOTES'),
            ('STG_ACCOUNT',  'ACCOUNT_NUMBER','RAW', 'BANKING', 'ACCOUNT',      'ACCOUNT_NUMBER','ANALYTICS', 'MARTS', 'DEPOSITS_DAILY','ACCOUNT_NUMBER'),
            ('STG_CARD',     'CARD_NUMBER',   'RAW', 'BANKING', 'CARD',         'CARD_NUMBER',   NULL,        NULL,    NULL,            NULL),
            ('STG_TRANSACTIONS', 'REFERENCE', 'RAW', 'BANKING', 'TRANSACTIONS', 'REFERENCE',     NULL,        NULL,    NULL,            NULL),
            ('STG_TRANSACTIONS', 'MEMO',      'RAW', 'BANKING', 'TRANSACTIONS', 'MEMO',          NULL,        NULL,    NULL,            NULL)
        AS M
        (
            STAGING_TABLE_NAME,
            STAGING_COLUMN_NAME,
            RAW_DATABASE_NAME,
            RAW_SCHEMA_NAME,
            RAW_TABLE_NAME,
            RAW_COLUMN_NAME,
            MART_DATABASE_NAME,
            MART_SCHEMA_NAME,
            MART_TABLE_NAME,
            MART_COLUMN_NAME
        )
    ),
    RAW_TARGETS AS
    (
        SELECT
            A.REVIEW_ID,
            M.RAW_DATABASE_NAME AS DATABASE_NAME,
            M.RAW_SCHEMA_NAME AS SCHEMA_NAME,
            M.RAW_TABLE_NAME AS OBJECT_NAME,
            M.RAW_COLUMN_NAME AS COLUMN_NAME,
            A.APPROVED_CLASSIFICATION AS TAG_VALUE,
            'REVIEW_ID=' || A.REVIEW_ID || ':RAW' AS SOURCE_REFERENCE
        FROM APPROVED A
        INNER JOIN COLUMN_MAP M
            ON M.STAGING_TABLE_NAME = A.STAGING_TABLE_NAME
           AND M.STAGING_COLUMN_NAME = A.STAGING_COLUMN_NAME
    ),
    MART_TARGETS AS
    (
        SELECT
            A.REVIEW_ID,
            M.MART_DATABASE_NAME AS DATABASE_NAME,
            M.MART_SCHEMA_NAME AS SCHEMA_NAME,
            M.MART_TABLE_NAME AS OBJECT_NAME,
            M.MART_COLUMN_NAME AS COLUMN_NAME,
            A.APPROVED_CLASSIFICATION AS TAG_VALUE,
            'REVIEW_ID=' || A.REVIEW_ID || ':MART' AS SOURCE_REFERENCE
        FROM APPROVED A
        INNER JOIN COLUMN_MAP M
            ON M.STAGING_TABLE_NAME = A.STAGING_TABLE_NAME
           AND M.STAGING_COLUMN_NAME = A.STAGING_COLUMN_NAME
        WHERE M.MART_TABLE_NAME IS NOT NULL
    )
    SELECT
        DATABASE_NAME,
        SCHEMA_NAME,
        OBJECT_NAME,
        COLUMN_NAME,
        'COLUMN' AS OBJECT_LEVEL,
        'TABLE' AS OBJECT_TYPE,
        'CLASSIFICATION' AS TAG_NAME,
        TAG_VALUE,
        'CLASSIFICATION_REVIEW' AS SOURCE_TYPE,
        SOURCE_REFERENCE,
        'Confirmed classification propagated from approved STAGING review'
            AS ASSIGNMENT_REASON,
        210 AS APPLY_ORDER
    FROM RAW_TARGETS

    UNION ALL

    SELECT
        DATABASE_NAME,
        SCHEMA_NAME,
        OBJECT_NAME,
        COLUMN_NAME,
        'COLUMN',
        'TABLE',
        'CLASSIFICATION',
        TAG_VALUE,
        'CLASSIFICATION_REVIEW',
        SOURCE_REFERENCE,
        'Confirmed classification propagated to MART exposed sensitive field',
        220
    FROM MART_TARGETS
) S
ON  T.DATABASE_NAME = S.DATABASE_NAME
AND T.SCHEMA_NAME = S.SCHEMA_NAME
AND T.OBJECT_NAME = S.OBJECT_NAME
AND T.COLUMN_NAME = S.COLUMN_NAME
AND T.OBJECT_LEVEL = S.OBJECT_LEVEL
AND T.TAG_NAME = S.TAG_NAME
WHEN MATCHED THEN UPDATE SET
    TAG_VALUE = S.TAG_VALUE,
    OBJECT_TYPE = S.OBJECT_TYPE,
    SOURCE_TYPE = S.SOURCE_TYPE,
    SOURCE_REFERENCE = S.SOURCE_REFERENCE,
    ASSIGNMENT_REASON = S.ASSIGNMENT_REASON,
    APPLY_ORDER = S.APPLY_ORDER,
    ACTIVE_FLAG = TRUE,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
(
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    COLUMN_NAME,
    OBJECT_LEVEL,
    OBJECT_TYPE,
    TAG_NAME,
    TAG_VALUE,
    SOURCE_TYPE,
    SOURCE_REFERENCE,
    ASSIGNMENT_REASON,
    APPLY_ORDER,
    ACTIVE_FLAG
)
VALUES
(
    S.DATABASE_NAME,
    S.SCHEMA_NAME,
    S.OBJECT_NAME,
    S.COLUMN_NAME,
    S.OBJECT_LEVEL,
    S.OBJECT_TYPE,
    S.TAG_NAME,
    S.TAG_VALUE,
    S.SOURCE_TYPE,
    S.SOURCE_REFERENCE,
    S.ASSIGNMENT_REASON,
    S.APPLY_ORDER,
    TRUE
);

CALL GOVERNANCE.CATALOG.APPLY_TAG_ASSIGNMENTS();

SELECT
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    COLUMN_NAME,
    TAG_NAME,
    TAG_VALUE,
    SOURCE_TYPE,
    SOURCE_REFERENCE,
    ACTIVE_FLAG
FROM GOVERNANCE.CATALOG.TAG_ASSIGNMENT
WHERE TAG_NAME = 'CLASSIFICATION'
ORDER BY
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    COLUMN_NAME;
