/*==============================================================================
 AVIDIA BANK - VALIDATE CLASSIFICATION
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;

SELECT
    GOVERNANCE.CATALOG.STAGING_CLASSIFICATION_PROFILE!DESCRIBE()
        AS PROFILE_CONFIGURATION;

SELECT
    GOVERNANCE.CATALOG.AVIDIA_ACCOUNT_NUMBER_CLASSIFIER!LIST()
        AS CUSTOM_CLASSIFIER_CONFIGURATION;

SELECT
    COUNT(*) AS CLASSIFICATION_CANDIDATE_COUNT
FROM GOVERNANCE.CATALOG.CLASSIFICATION_CANDIDATE
WHERE ACTIVE_FLAG = TRUE;

!source classification/08_precision_recall.sql;

SELECT
    REVIEW_STATUS,
    COUNT(*) AS REVIEW_COUNT
FROM GOVERNANCE.CATALOG.CLASSIFICATION_REVIEW_QUEUE
GROUP BY REVIEW_STATUS
ORDER BY REVIEW_STATUS;

SELECT
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    COLUMN_NAME,
    TAG_VALUE AS CONFIRMED_CLASSIFICATION,
    SOURCE_TYPE,
    SOURCE_REFERENCE
FROM GOVERNANCE.CATALOG.TAG_ASSIGNMENT
WHERE TAG_NAME = 'CLASSIFICATION'
  AND ACTIVE_FLAG = TRUE
ORDER BY
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    COLUMN_NAME;

SELECT
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    COLUMN_NAME,
    TAG_VALUE,
    SOURCE_TYPE,
    SOURCE_REFERENCE,
    CASE
        WHEN SOURCE_TYPE = 'CLASSIFICATION_REVIEW'
         AND SOURCE_REFERENCE ILIKE 'REVIEW_ID=%'
            THEN 'PASS'
        ELSE 'FAIL'
    END AS APPROVED_SOURCE_STATUS
FROM GOVERNANCE.CATALOG.TAG_ASSIGNMENT
WHERE TAG_NAME = 'CLASSIFICATION'
  AND ACTIVE_FLAG = TRUE
  AND (
        SOURCE_TYPE <> 'CLASSIFICATION_REVIEW'
        OR SOURCE_REFERENCE NOT ILIKE 'REVIEW_ID=%'
      );

SELECT
    'Rows above indicate policy-driving CLASSIFICATION tags without approved review source.'
        AS VALIDATION_NOTE;
