SELECT
    R.REVIEW_ID,
    R.TABLE_NAME,
    R.COLUMN_NAME,

    -- Snowflake classification result
    R.SEMANTIC_CATEGORY,
    R.PRIVACY_CATEGORY,
    R.CONFIDENCE,
    R.PROPOSED_CLASSIFICATION,

    -- Sealed ground truth
    CASE
        WHEN S.STAGING_COLUMN_NAME IS NOT NULL THEN 'YES'
        ELSE 'NO'
    END AS IN_SEALED_LIST,

    S.EXPECTED_SENSITIVE,
    S.EXPECTED_SENSITIVE_CONTENT,
    S.DELIBERATELY_MISLABELED,

    -- Comparison result
    CASE
        WHEN S.STAGING_COLUMN_NAME IS NULL
            THEN 'NOT_IN_SEALED_LIST'

        WHEN S.EXPECTED_SENSITIVE = TRUE
            THEN 'EXPECTED_SENSITIVE'

        WHEN S.DELIBERATELY_MISLABELED = TRUE
            THEN 'DELIBERATELY_MISLABELED'

        ELSE 'REVIEW_REQUIRED'
    END AS SEALED_LIST_RESULT

FROM GOVERNANCE.CATALOG.CLASSIFICATION_REVIEW_QUEUE R

LEFT JOIN GOVERNANCE.CATALOG.SEALED_SENSITIVE_COLUMN S
    ON UPPER(R.TABLE_NAME) = UPPER(S.STAGING_TABLE_NAME)
   AND UPPER(R.COLUMN_NAME) = UPPER(S.STAGING_COLUMN_NAME)

WHERE R.REVIEW_STATUS = 'PENDING'

ORDER BY R.REVIEW_ID;