SELECT
    LOAN_ID,
    OUTSTANDING_AMOUNT,
    TOTAL_COLLATERAL_VALUE,
    LOAN_TO_VALUE_RATIO,
    OUTSTANDING_AMOUNT / TOTAL_COLLATERAL_VALUE AS EXPECTED_LOAN_TO_VALUE_RATIO
FROM {{ ref('loan_portfolio') }}
WHERE TOTAL_COLLATERAL_VALUE > 0
    AND OUTSTANDING_AMOUNT IS NOT NULL
    AND ABS(LOAN_TO_VALUE_RATIO - (OUTSTANDING_AMOUNT / TOTAL_COLLATERAL_VALUE)) > 0.000001
