SELECT
    LOAN_ID,
    OUTSTANDING_AMOUNT,
    COLLATERAL_COUNT,
    TOTAL_COLLATERAL_VALUE,
    LOAN_TO_VALUE_RATIO
FROM {{ ref('loan_portfolio') }}
WHERE COLLATERAL_COUNT < 0
    OR TOTAL_COLLATERAL_VALUE < 0
    OR (COALESCE(TOTAL_COLLATERAL_VALUE, 0) = 0 AND LOAN_TO_VALUE_RATIO IS NOT NULL)
    OR (
        COALESCE(TOTAL_COLLATERAL_VALUE, 0) > 0
        AND OUTSTANDING_AMOUNT IS NOT NULL
        AND LOAN_TO_VALUE_RATIO IS NULL
    )
