SELECT
    CUSTOMER_ID,
    ACCOUNT_COUNT,
    ACTIVE_ACCOUNT_COUNT,
    TRANSACTION_COUNT,
    LOAN_COUNT,
    CARD_COUNT,
    ACTIVE_CARD_COUNT
FROM {{ ref('customer_360') }}
WHERE
    ACCOUNT_COUNT < 0
    OR ACTIVE_ACCOUNT_COUNT < 0
    OR ACTIVE_ACCOUNT_COUNT > ACCOUNT_COUNT
    OR TRANSACTION_COUNT < 0
    OR LOAN_COUNT < 0
    OR CARD_COUNT < 0
    OR ACTIVE_CARD_COUNT < 0
    OR ACTIVE_CARD_COUNT > CARD_COUNT
