/*==============================================================================
 AVIDIA BANK - PROTECTION PHASE PERMISSIONS
 File: protection/01_permissions.sql

 Purpose:
   Privileges required for confirmed-classification driven masking and one
   branch-scoped row access policy, with proof on RAW and MART objects.

 Design:
   - STAGING remains an internal processing zone; no consumer grants are added.
   - Tag-based masking is driven by GOVERNANCE.TAGS.CLASSIFICATION.
   - Row access is attached directly to selected RAW and MART tables.
==============================================================================*/

USE ROLE SECURITYADMIN;

-- Governance-policy administration.
GRANT USAGE ON DATABASE GOVERNANCE
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT CREATE MASKING POLICY
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT CREATE ROW ACCESS POLICY
ON SCHEMA GOVERNANCE.CATALOG
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT APPLY MASKING POLICY
ON ACCOUNT
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT APPLY ROW ACCESS POLICY
ON ACCOUNT
TO ROLE DATA_GOVERNANCE_ADMIN;

-- Allow the governance role to apply the existing CLASSIFICATION tag.
GRANT APPLY ON TAG GOVERNANCE.TAGS.CLASSIFICATION
TO ROLE DATA_GOVERNANCE_ADMIN;

-- RAW objects used for protection evidence.
GRANT USAGE ON DATABASE RAW
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE ON SCHEMA RAW.BANKING
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT SELECT
ON ALL TABLES IN SCHEMA RAW.BANKING
TO ROLE DATA_GOVERNANCE_ADMIN;

-- MART objects used for protection evidence.
GRANT USAGE ON DATABASE ANALYTICS
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE ON SCHEMA ANALYTICS.MARTS
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT SELECT
ON ALL TABLES IN SCHEMA ANALYTICS.MARTS
TO ROLE DATA_GOVERNANCE_ADMIN;

-- Consumer roles: only grant the surfaces needed for role-based evidence.
-- No STAGING access is granted here.

GRANT USAGE ON DATABASE RAW TO ROLE DATA_OWNER;
GRANT USAGE ON SCHEMA RAW.BANKING TO ROLE DATA_OWNER;
GRANT SELECT ON TABLE RAW.BANKING.CUSTOMER TO ROLE DATA_OWNER;
GRANT SELECT ON TABLE RAW.BANKING.CARD TO ROLE DATA_OWNER;
GRANT SELECT ON TABLE RAW.BANKING.ACCOUNT TO ROLE DATA_OWNER;

GRANT USAGE ON DATABASE ANALYTICS TO ROLE DATA_OWNER;
GRANT USAGE ON SCHEMA ANALYTICS.MARTS TO ROLE DATA_OWNER;
GRANT SELECT ON TABLE ANALYTICS.MARTS.CUSTOMER_360 TO ROLE DATA_OWNER;
GRANT SELECT ON TABLE ANALYTICS.MARTS.DEPOSITS_DAILY TO ROLE DATA_OWNER;

GRANT USAGE ON DATABASE RAW TO ROLE DATA_STEWARD;
GRANT USAGE ON SCHEMA RAW.BANKING TO ROLE DATA_STEWARD;
GRANT SELECT ON TABLE RAW.BANKING.CUSTOMER TO ROLE DATA_STEWARD;
GRANT SELECT ON TABLE RAW.BANKING.CARD TO ROLE DATA_STEWARD;
GRANT SELECT ON TABLE RAW.BANKING.ACCOUNT TO ROLE DATA_STEWARD;

GRANT USAGE ON DATABASE ANALYTICS TO ROLE DATA_STEWARD;
GRANT USAGE ON SCHEMA ANALYTICS.MARTS TO ROLE DATA_STEWARD;
GRANT SELECT ON TABLE ANALYTICS.MARTS.CUSTOMER_360 TO ROLE DATA_STEWARD;
GRANT SELECT ON TABLE ANALYTICS.MARTS.DEPOSITS_DAILY TO ROLE DATA_STEWARD;

GRANT USAGE ON DATABASE RAW TO ROLE DEPOSITS_ANALYST;
GRANT USAGE ON SCHEMA RAW.BANKING TO ROLE DEPOSITS_ANALYST;
GRANT SELECT ON TABLE RAW.BANKING.CUSTOMER TO ROLE DEPOSITS_ANALYST;
GRANT SELECT ON TABLE RAW.BANKING.CARD TO ROLE DEPOSITS_ANALYST;
GRANT SELECT ON TABLE RAW.BANKING.ACCOUNT TO ROLE DEPOSITS_ANALYST;

GRANT USAGE ON DATABASE ANALYTICS TO ROLE DEPOSITS_ANALYST;
GRANT USAGE ON SCHEMA ANALYTICS.MARTS TO ROLE DEPOSITS_ANALYST;
GRANT SELECT ON TABLE ANALYTICS.MARTS.CUSTOMER_360 TO ROLE DEPOSITS_ANALYST;
GRANT SELECT ON TABLE ANALYTICS.MARTS.DEPOSITS_DAILY TO ROLE DEPOSITS_ANALYST;

GRANT USAGE ON DATABASE RAW TO ROLE BRANCH_HUDSON;
GRANT USAGE ON SCHEMA RAW.BANKING TO ROLE BRANCH_HUDSON;
GRANT SELECT ON TABLE RAW.BANKING.ACCOUNT TO ROLE BRANCH_HUDSON;

GRANT USAGE ON DATABASE ANALYTICS TO ROLE BRANCH_HUDSON;
GRANT USAGE ON SCHEMA ANALYTICS.MARTS TO ROLE BRANCH_HUDSON;
GRANT SELECT ON TABLE ANALYTICS.MARTS.DEPOSITS_DAILY TO ROLE BRANCH_HUDSON;

-- Verification.
SHOW GRANTS TO ROLE DATA_GOVERNANCE_ADMIN;
