/*==============================================================================
 AVIDIA BANK - APPLY BRANCH ROW ACCESS POLICY

 Purpose:
   Apply the same branch-scoped policy directly to:
     - RAW.BANKING.ACCOUNT
     - ANALYTICS.MARTS.DEPOSITS_DAILY
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;

ALTER TABLE RAW.BANKING.ACCOUNT
    DROP ALL ROW ACCESS POLICIES;

ALTER TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
    DROP ALL ROW ACCESS POLICIES;

ALTER TABLE RAW.BANKING.ACCOUNT
    ADD ROW ACCESS POLICY
        GOVERNANCE.CATALOG.BRANCH_SCOPE_ROW_ACCESS_POLICY
    ON (BRANCH_ID);

ALTER TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
    ADD ROW ACCESS POLICY
        GOVERNANCE.CATALOG.BRANCH_SCOPE_ROW_ACCESS_POLICY
    ON (BRANCH_ID);

SELECT
    POLICY_DB,
    POLICY_SCHEMA,
    POLICY_NAME,
    POLICY_KIND,
    REF_DATABASE_NAME,
    REF_SCHEMA_NAME,
    REF_ENTITY_NAME,
    REF_COLUMN_NAME,
    POLICY_STATUS
FROM TABLE
(
    RAW.INFORMATION_SCHEMA.POLICY_REFERENCES
    (
        REF_ENTITY_NAME => 'RAW.BANKING.ACCOUNT',
        REF_ENTITY_DOMAIN => 'TABLE'
    )
)
WHERE POLICY_NAME = 'BRANCH_SCOPE_ROW_ACCESS_POLICY'

UNION ALL

SELECT
    POLICY_DB,
    POLICY_SCHEMA,
    POLICY_NAME,
    POLICY_KIND,
    REF_DATABASE_NAME,
    REF_SCHEMA_NAME,
    REF_ENTITY_NAME,
    REF_COLUMN_NAME,
    POLICY_STATUS
FROM TABLE
(
    ANALYTICS.INFORMATION_SCHEMA.POLICY_REFERENCES
    (
        REF_ENTITY_NAME => 'ANALYTICS.MARTS.DEPOSITS_DAILY',
        REF_ENTITY_DOMAIN => 'TABLE'
    )
)
WHERE POLICY_NAME = 'BRANCH_SCOPE_ROW_ACCESS_POLICY';
