/*==============================================================================
 AVIDIA BANK - VALIDATE MASKING BY ROLE

 Purpose:
   Show comparable RAW and MART queries for role-based masking evidence.
==============================================================================*/

USE WAREHOUSE WH_GOVERNANCE_XS;

USE ROLE DATA_OWNER;

SELECT
    'DATA_OWNER_RAW_CUSTOMER' AS EVIDENCE_QUERY,
    CUSTOMER_ID,
    TAX_ID,
    DATE_OF_BIRTH,
    EMAIL,
    PHONE
FROM RAW.BANKING.CUSTOMER
WHERE TAX_ID IS NOT NULL
LIMIT 5;

SELECT
    'DATA_OWNER_MART_CUSTOMER_360' AS EVIDENCE_QUERY,
    CUSTOMER_ID,
    TAX_ID,
    DATE_OF_BIRTH,
    EMAIL,
    PHONE
FROM ANALYTICS.MARTS.CUSTOMER_360
WHERE TAX_ID IS NOT NULL
LIMIT 5;

USE ROLE DATA_STEWARD;

SELECT
    'DATA_STEWARD_RAW_CUSTOMER' AS EVIDENCE_QUERY,
    CUSTOMER_ID,
    TAX_ID,
    DATE_OF_BIRTH,
    EMAIL,
    PHONE
FROM RAW.BANKING.CUSTOMER
WHERE TAX_ID IS NOT NULL
LIMIT 5;

SELECT
    'DATA_STEWARD_MART_CUSTOMER_360' AS EVIDENCE_QUERY,
    CUSTOMER_ID,
    TAX_ID,
    DATE_OF_BIRTH,
    EMAIL,
    PHONE
FROM ANALYTICS.MARTS.CUSTOMER_360
WHERE TAX_ID IS NOT NULL
LIMIT 5;

USE ROLE DEPOSITS_ANALYST;

SELECT
    'DEPOSITS_ANALYST_RAW_CUSTOMER' AS EVIDENCE_QUERY,
    CUSTOMER_ID,
    TAX_ID,
    DATE_OF_BIRTH,
    EMAIL,
    PHONE
FROM RAW.BANKING.CUSTOMER
WHERE TAX_ID IS NOT NULL
LIMIT 5;

SELECT
    'DEPOSITS_ANALYST_MART_CUSTOMER_360' AS EVIDENCE_QUERY,
    CUSTOMER_ID,
    TAX_ID,
    DATE_OF_BIRTH,
    EMAIL,
    PHONE
FROM ANALYTICS.MARTS.CUSTOMER_360
WHERE TAX_ID IS NOT NULL
LIMIT 5;

SELECT
    'DEPOSITS_ANALYST_RAW_CARD' AS EVIDENCE_QUERY,
    CARD_ID,
    CARD_NUMBER
FROM RAW.BANKING.CARD
WHERE CARD_NUMBER IS NOT NULL
LIMIT 5;

SELECT
    'DEPOSITS_ANALYST_MART_DEPOSITS_DAILY' AS EVIDENCE_QUERY,
    ACCOUNT_ID,
    BUSINESS_DATE,
    ACCOUNT_NUMBER
FROM ANALYTICS.MARTS.DEPOSITS_DAILY
WHERE ACCOUNT_NUMBER IS NOT NULL
LIMIT 5;
