/*==============================================================================
 AVIDIA BANK - VALIDATE BRANCH ROW ACCESS
==============================================================================*/

USE WAREHOUSE WH_GOVERNANCE_XS;

USE ROLE DATA_OWNER;

SELECT
    'DATA_OWNER_RAW_ACCOUNT' AS EVIDENCE_QUERY,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT BRANCH_ID) AS DISTINCT_BRANCH_COUNT,
    LISTAGG(DISTINCT BRANCH_ID, ', ')
        WITHIN GROUP (ORDER BY BRANCH_ID) AS BRANCH_IDS
FROM RAW.BANKING.ACCOUNT;

SELECT
    'DATA_OWNER_MART_DEPOSITS_DAILY' AS EVIDENCE_QUERY,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT BRANCH_ID) AS DISTINCT_BRANCH_COUNT,
    LISTAGG(DISTINCT BRANCH_ID, ', ')
        WITHIN GROUP (ORDER BY BRANCH_ID) AS BRANCH_IDS
FROM ANALYTICS.MARTS.DEPOSITS_DAILY;

USE ROLE DATA_STEWARD;

SELECT
    'DATA_STEWARD_RAW_ACCOUNT' AS EVIDENCE_QUERY,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT BRANCH_ID) AS DISTINCT_BRANCH_COUNT,
    LISTAGG(DISTINCT BRANCH_ID, ', ')
        WITHIN GROUP (ORDER BY BRANCH_ID) AS BRANCH_IDS
FROM RAW.BANKING.ACCOUNT;

SELECT
    'DATA_STEWARD_MART_DEPOSITS_DAILY' AS EVIDENCE_QUERY,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT BRANCH_ID) AS DISTINCT_BRANCH_COUNT,
    LISTAGG(DISTINCT BRANCH_ID, ', ')
        WITHIN GROUP (ORDER BY BRANCH_ID) AS BRANCH_IDS
FROM ANALYTICS.MARTS.DEPOSITS_DAILY;

USE ROLE BRANCH_HUDSON;

SELECT
    'BRANCH_HUDSON_RAW_ACCOUNT' AS EVIDENCE_QUERY,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT BRANCH_ID) AS DISTINCT_BRANCH_COUNT,
    LISTAGG(DISTINCT BRANCH_ID, ', ')
        WITHIN GROUP (ORDER BY BRANCH_ID) AS BRANCH_IDS
FROM RAW.BANKING.ACCOUNT;

SELECT
    'BRANCH_HUDSON_MART_DEPOSITS_DAILY' AS EVIDENCE_QUERY,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT BRANCH_ID) AS DISTINCT_BRANCH_COUNT,
    LISTAGG(DISTINCT BRANCH_ID, ', ')
        WITHIN GROUP (ORDER BY BRANCH_ID) AS BRANCH_IDS
FROM ANALYTICS.MARTS.DEPOSITS_DAILY;
