/*==============================================================================
 AVIDIA BANK - SENSITIVE POLICY GAP REPORT

 Purpose:
   Starting from approved sensitive-column governance state, report confirmed
   RAW/MART classification targets that do not have active tag-based masking.

 Expected final result:
   0 rows
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;

WITH APPROVED_TARGETS AS
(
    SELECT
        DATABASE_NAME,
        SCHEMA_NAME,
        OBJECT_NAME,
        COLUMN_NAME,
        TAG_VALUE AS CONFIRMED_CLASSIFICATION
    FROM GOVERNANCE.CATALOG.TAG_ASSIGNMENT
    WHERE TAG_NAME = 'CLASSIFICATION'
      AND SOURCE_TYPE = 'CLASSIFICATION_REVIEW'
      AND ACTIVE_FLAG = TRUE
      AND (
            (DATABASE_NAME = 'RAW' AND SCHEMA_NAME = 'BANKING')
            OR (DATABASE_NAME = 'ANALYTICS' AND SCHEMA_NAME = 'MARTS')
          )
),
ACTUAL_TAGS AS
(
    SELECT
        'RAW' AS DATABASE_NAME,
        'BANKING' AS SCHEMA_NAME,
        'CUSTOMER' AS OBJECT_NAME,
        COLUMN_NAME,
        TAG_VALUE
    FROM TABLE
    (
        RAW.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS
        (
            'RAW.BANKING.CUSTOMER',
            'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'

    UNION ALL

    SELECT
        'RAW',
        'BANKING',
        'CARD',
        COLUMN_NAME,
        TAG_VALUE
    FROM TABLE
    (
        RAW.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS
        (
            'RAW.BANKING.CARD',
            'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'

    UNION ALL

    SELECT
        'RAW',
        'BANKING',
        'ACCOUNT',
        COLUMN_NAME,
        TAG_VALUE
    FROM TABLE
    (
        RAW.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS
        (
            'RAW.BANKING.ACCOUNT',
            'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'

    UNION ALL

    SELECT
        'ANALYTICS',
        'MARTS',
        'CUSTOMER_360',
        COLUMN_NAME,
        TAG_VALUE
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS
        (
            'ANALYTICS.MARTS.CUSTOMER_360',
            'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'

    UNION ALL

    SELECT
        'ANALYTICS',
        'MARTS',
        'DEPOSITS_DAILY',
        COLUMN_NAME,
        TAG_VALUE
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS
        (
            'ANALYTICS.MARTS.DEPOSITS_DAILY',
            'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'
),
POLICY_REFS AS
(
    SELECT
        REF_DATABASE_NAME AS DATABASE_NAME,
        REF_SCHEMA_NAME AS SCHEMA_NAME,
        REF_ENTITY_NAME AS OBJECT_NAME,
        REF_COLUMN_NAME AS COLUMN_NAME,
        POLICY_NAME,
        POLICY_STATUS,
        TAG_NAME
    FROM TABLE
    (
        RAW.INFORMATION_SCHEMA.POLICY_REFERENCES
        (
            REF_ENTITY_NAME => 'RAW.BANKING.CUSTOMER',
            REF_ENTITY_DOMAIN => 'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'

    UNION ALL

    SELECT
        REF_DATABASE_NAME,
        REF_SCHEMA_NAME,
        REF_ENTITY_NAME,
        REF_COLUMN_NAME,
        POLICY_NAME,
        POLICY_STATUS,
        TAG_NAME
    FROM TABLE
    (
        RAW.INFORMATION_SCHEMA.POLICY_REFERENCES
        (
            REF_ENTITY_NAME => 'RAW.BANKING.CARD',
            REF_ENTITY_DOMAIN => 'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'

    UNION ALL

    SELECT
        REF_DATABASE_NAME,
        REF_SCHEMA_NAME,
        REF_ENTITY_NAME,
        REF_COLUMN_NAME,
        POLICY_NAME,
        POLICY_STATUS,
        TAG_NAME
    FROM TABLE
    (
        RAW.INFORMATION_SCHEMA.POLICY_REFERENCES
        (
            REF_ENTITY_NAME => 'RAW.BANKING.ACCOUNT',
            REF_ENTITY_DOMAIN => 'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'

    UNION ALL

    SELECT
        REF_DATABASE_NAME,
        REF_SCHEMA_NAME,
        REF_ENTITY_NAME,
        REF_COLUMN_NAME,
        POLICY_NAME,
        POLICY_STATUS,
        TAG_NAME
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.POLICY_REFERENCES
        (
            REF_ENTITY_NAME => 'ANALYTICS.MARTS.CUSTOMER_360',
            REF_ENTITY_DOMAIN => 'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'

    UNION ALL

    SELECT
        REF_DATABASE_NAME,
        REF_SCHEMA_NAME,
        REF_ENTITY_NAME,
        REF_COLUMN_NAME,
        POLICY_NAME,
        POLICY_STATUS,
        TAG_NAME
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.POLICY_REFERENCES
        (
            REF_ENTITY_NAME => 'ANALYTICS.MARTS.DEPOSITS_DAILY',
            REF_ENTITY_DOMAIN => 'TABLE'
        )
    )
    WHERE TAG_DATABASE = 'GOVERNANCE'
      AND TAG_SCHEMA = 'TAGS'
      AND TAG_NAME = 'CLASSIFICATION'
)
SELECT
    T.DATABASE_NAME,
    T.SCHEMA_NAME,
    T.OBJECT_NAME,
    T.COLUMN_NAME,
    T.CONFIRMED_CLASSIFICATION,
    A.TAG_VALUE AS ACTUAL_TAG_VALUE,
    P.POLICY_NAME,
    P.POLICY_STATUS,
    CASE
        WHEN A.COLUMN_NAME IS NULL THEN 'MISSING_CONFIRMED_TAG'
        WHEN P.COLUMN_NAME IS NULL THEN 'MISSING_MASKING_POLICY'
        WHEN P.POLICY_STATUS <> 'ACTIVE' THEN 'MASKING_POLICY_NOT_ACTIVE'
    END AS GAP_REASON
FROM APPROVED_TARGETS T
LEFT JOIN ACTUAL_TAGS A
    ON A.DATABASE_NAME = T.DATABASE_NAME
   AND A.SCHEMA_NAME = T.SCHEMA_NAME
   AND A.OBJECT_NAME = T.OBJECT_NAME
   AND A.COLUMN_NAME = T.COLUMN_NAME
LEFT JOIN POLICY_REFS P
    ON P.DATABASE_NAME = T.DATABASE_NAME
   AND P.SCHEMA_NAME = T.SCHEMA_NAME
   AND P.OBJECT_NAME = T.OBJECT_NAME
   AND P.COLUMN_NAME = T.COLUMN_NAME
   AND P.POLICY_STATUS = 'ACTIVE'
WHERE A.COLUMN_NAME IS NULL
   OR P.COLUMN_NAME IS NULL
   OR P.POLICY_STATUS <> 'ACTIVE'
ORDER BY
    T.DATABASE_NAME,
    T.SCHEMA_NAME,
    T.OBJECT_NAME,
    T.COLUMN_NAME;
