USE ROLE ACCOUNTADMIN;

USE WAREHOUSE WH_GOVERNANCE_XS;

CREATE DATABASE IF NOT EXISTS ANALYTICS;

CREATE SCHEMA IF NOT EXISTS ANALYTICS.STAGING
    COMMENT = 'Standardized and cleansed banking data derived from RAW.BANKING';

CREATE SCHEMA IF NOT EXISTS ANALYTICS.MARTS
    COMMENT = 'Business-ready governed banking data products';


GRANT USAGE
ON DATABASE ANALYTICS
TO ROLE SYSADMIN;

GRANT CREATE SCHEMA
ON DATABASE ANALYTICS
TO ROLE SYSADMIN;

GRANT USAGE
ON DATABASE ANALYTICS
TO ROLE DATA_ENGINEER;

GRANT USAGE
ON SCHEMA ANALYTICS.STAGING
TO ROLE DATA_ENGINEER;

GRANT CREATE TABLE
ON SCHEMA ANALYTICS.STAGING
TO ROLE DATA_ENGINEER;

GRANT CREATE VIEW
ON SCHEMA ANALYTICS.STAGING
TO ROLE DATA_ENGINEER;