/*==============================================================================
  AVIDIA BANKING DATA GOVERNANCE
  File: transformations/staging/05_merge_account_daily_balance.sql

  Purpose:
      Standardize RAW.BANKING.ACCOUNT_DAILY_BALANCE and MERGE it into
      STG_ACCOUNT_DAILY_BALANCE.

  Logical grain:
      ACCOUNT_ID + BUSINESS_DATE

  Data-quality boundary:
      - Both grain columns must be present.
      - No timeliness, balance-accuracy, or account-FK filtering.
==============================================================================*/

USE ROLE DATA_ENGINEER;
USE WAREHOUSE WH_GOVERNANCE_XS;

MERGE INTO ANALYTICS.STAGING.STG_ACCOUNT_DAILY_BALANCE T
USING
(
    SELECT
        TRIM(ACCOUNT_ID)                       AS ACCOUNT_ID,
        BUSINESS_DATE,
        OPENING_BALANCE,
        CLOSING_BALANCE,
        AVAILABLE_BALANCE,
        NULLIF(UPPER(TRIM(CURRENCY)), '')      AS CURRENCY,
        NULLIF(UPPER(TRIM(SOURCE_SYSTEM)), '') AS SOURCE_SYSTEM,
        LOAD_TIMESTAMP
    FROM RAW.BANKING.ACCOUNT_DAILY_BALANCE
    WHERE ACCOUNT_ID IS NOT NULL
      AND TRIM(ACCOUNT_ID) <> ''
      AND BUSINESS_DATE IS NOT NULL
) S
ON  T.ACCOUNT_ID    = S.ACCOUNT_ID
AND T.BUSINESS_DATE = S.BUSINESS_DATE

WHEN MATCHED
AND HASH(
        T.OPENING_BALANCE, T.CLOSING_BALANCE, T.AVAILABLE_BALANCE,
        T.CURRENCY, T.SOURCE_SYSTEM, T.LOAD_TIMESTAMP
    )
    <>
    HASH(
        S.OPENING_BALANCE, S.CLOSING_BALANCE, S.AVAILABLE_BALANCE,
        S.CURRENCY, S.SOURCE_SYSTEM, S.LOAD_TIMESTAMP
    )
THEN UPDATE SET
    T.OPENING_BALANCE     = S.OPENING_BALANCE,
    T.CLOSING_BALANCE     = S.CLOSING_BALANCE,
    T.AVAILABLE_BALANCE   = S.AVAILABLE_BALANCE,
    T.CURRENCY            = S.CURRENCY,
    T.SOURCE_SYSTEM       = S.SOURCE_SYSTEM,
    T.LOAD_TIMESTAMP      = S.LOAD_TIMESTAMP,
    T.STG_UPDATED_AT      = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
    ACCOUNT_ID, BUSINESS_DATE, OPENING_BALANCE,
    CLOSING_BALANCE, AVAILABLE_BALANCE, CURRENCY,
    SOURCE_SYSTEM, LOAD_TIMESTAMP
)
VALUES
(
    S.ACCOUNT_ID, S.BUSINESS_DATE, S.OPENING_BALANCE,
    S.CLOSING_BALANCE, S.AVAILABLE_BALANCE, S.CURRENCY,
    S.SOURCE_SYSTEM, S.LOAD_TIMESTAMP
);

SELECT
    (SELECT COUNT(*) FROM RAW.BANKING.ACCOUNT_DAILY_BALANCE) AS RAW_ROWS,
    (SELECT COUNT(*) FROM ANALYTICS.STAGING.STG_ACCOUNT_DAILY_BALANCE) AS STAGING_ROWS;
