/*==============================================================================
  AVIDIA BANKING DATA GOVERNANCE
  File: transformations/staging/08_merge_gl_control_total.sql

  Purpose:
      Standardize RAW.BANKING.GL_CONTROL_TOTAL and MERGE it into
      STG_GL_CONTROL_TOTAL.

  Important:
      GL values are preserved so Block 3 can later prove accuracy/reconciliation.

  Data-quality boundary:
      - GL_CONTROL_ID must be present.
      - No reconciliation, timeliness, or financial-validity filtering.
==============================================================================*/

USE ROLE DATA_ENGINEER;
USE WAREHOUSE WH_GOVERNANCE_XS;

MERGE INTO ANALYTICS.STAGING.STG_GL_CONTROL_TOTAL T
USING
(
    SELECT
        TRIM(GL_CONTROL_ID)                       AS GL_CONTROL_ID,
        BUSINESS_DATE,
        NULLIF(UPPER(TRIM(GL_ACCOUNT_CODE)), '')  AS GL_ACCOUNT_CODE,
        NULLIF(UPPER(TRIM(PRODUCT_TYPE)), '')     AS PRODUCT_TYPE,
        NULLIF(UPPER(TRIM(CURRENCY)), '')         AS CURRENCY,
        CONTROL_TOTAL,
        TRANSACTION_COUNT,
        NULLIF(UPPER(TRIM(SOURCE_SYSTEM)), '')    AS SOURCE_SYSTEM,
        LOAD_TIMESTAMP
    FROM RAW.BANKING.GL_CONTROL_TOTAL
    WHERE GL_CONTROL_ID IS NOT NULL
      AND TRIM(GL_CONTROL_ID) <> ''
) S
ON T.GL_CONTROL_ID = S.GL_CONTROL_ID

WHEN MATCHED
AND HASH(
        T.BUSINESS_DATE, T.GL_ACCOUNT_CODE, T.PRODUCT_TYPE,
        T.CURRENCY, T.CONTROL_TOTAL, T.TRANSACTION_COUNT,
        T.SOURCE_SYSTEM, T.LOAD_TIMESTAMP
    )
    <>
    HASH(
        S.BUSINESS_DATE, S.GL_ACCOUNT_CODE, S.PRODUCT_TYPE,
        S.CURRENCY, S.CONTROL_TOTAL, S.TRANSACTION_COUNT,
        S.SOURCE_SYSTEM, S.LOAD_TIMESTAMP
    )
THEN UPDATE SET
    T.BUSINESS_DATE       = S.BUSINESS_DATE,
    T.GL_ACCOUNT_CODE     = S.GL_ACCOUNT_CODE,
    T.PRODUCT_TYPE        = S.PRODUCT_TYPE,
    T.CURRENCY            = S.CURRENCY,
    T.CONTROL_TOTAL       = S.CONTROL_TOTAL,
    T.TRANSACTION_COUNT   = S.TRANSACTION_COUNT,
    T.SOURCE_SYSTEM       = S.SOURCE_SYSTEM,
    T.LOAD_TIMESTAMP      = S.LOAD_TIMESTAMP,
    T.STG_UPDATED_AT      = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
    GL_CONTROL_ID, BUSINESS_DATE, GL_ACCOUNT_CODE,
    PRODUCT_TYPE, CURRENCY, CONTROL_TOTAL,
    TRANSACTION_COUNT, SOURCE_SYSTEM, LOAD_TIMESTAMP
)
VALUES
(
    S.GL_CONTROL_ID, S.BUSINESS_DATE, S.GL_ACCOUNT_CODE,
    S.PRODUCT_TYPE, S.CURRENCY, S.CONTROL_TOTAL,
    S.TRANSACTION_COUNT, S.SOURCE_SYSTEM, S.LOAD_TIMESTAMP
);

SELECT
    (SELECT COUNT(*) FROM RAW.BANKING.GL_CONTROL_TOTAL) AS RAW_ROWS,
    (SELECT COUNT(*) FROM ANALYTICS.STAGING.STG_GL_CONTROL_TOTAL) AS STAGING_ROWS;
