/*==============================================================================
  AVIDIA BANKING DATA GOVERNANCE
  File: transformations/staging/09_merge_loan.sql

  Purpose:
      Standardize RAW.BANKING.LOAN and MERGE it into STG_LOAN.

  Data-quality boundary:
      - LOAN_ID must be present.
      - No FK, status, credit-grade, maturity, or exposure validation here.
==============================================================================*/

USE ROLE DATA_ENGINEER;
USE WAREHOUSE WH_GOVERNANCE_XS;

MERGE INTO ANALYTICS.STAGING.STG_LOAN T
USING
(
    SELECT
        TRIM(LOAN_ID)                         AS LOAN_ID,
        NULLIF(TRIM(LOAN_NUMBER), '')         AS LOAN_NUMBER,
        NULLIF(TRIM(CUSTOMER_ID), '')         AS CUSTOMER_ID,
        NULLIF(TRIM(PRODUCT_ID), '')          AS PRODUCT_ID,
        NULLIF(TRIM(BRANCH_ID), '')           AS BRANCH_ID,
        NULLIF(TRIM(OFFICER_ID), '')          AS OFFICER_ID,
        NULLIF(UPPER(TRIM(LOAN_TYPE)), '')    AS LOAN_TYPE,
        LOAN_AMOUNT,
        OUTSTANDING_AMOUNT,
        INTEREST_RATE,
        TENURE_MONTHS,
        START_DATE,
        MATURITY_DATE,
        NULLIF(UPPER(TRIM(CREDIT_GRADE)), '') AS CREDIT_GRADE,
        NULLIF(UPPER(TRIM(LOAN_STATUS)), '')  AS LOAN_STATUS
    FROM RAW.BANKING.LOAN
    WHERE LOAN_ID IS NOT NULL
      AND TRIM(LOAN_ID) <> ''
) S
ON T.LOAN_ID = S.LOAN_ID

WHEN MATCHED
AND HASH(
        T.LOAN_NUMBER, T.CUSTOMER_ID, T.PRODUCT_ID, T.BRANCH_ID,
        T.OFFICER_ID, T.LOAN_TYPE, T.LOAN_AMOUNT, T.OUTSTANDING_AMOUNT,
        T.INTEREST_RATE, T.TENURE_MONTHS, T.START_DATE, T.MATURITY_DATE,
        T.CREDIT_GRADE, T.LOAN_STATUS
    )
    <>
    HASH(
        S.LOAN_NUMBER, S.CUSTOMER_ID, S.PRODUCT_ID, S.BRANCH_ID,
        S.OFFICER_ID, S.LOAN_TYPE, S.LOAN_AMOUNT, S.OUTSTANDING_AMOUNT,
        S.INTEREST_RATE, S.TENURE_MONTHS, S.START_DATE, S.MATURITY_DATE,
        S.CREDIT_GRADE, S.LOAN_STATUS
    )
THEN UPDATE SET
    T.LOAN_NUMBER         = S.LOAN_NUMBER,
    T.CUSTOMER_ID         = S.CUSTOMER_ID,
    T.PRODUCT_ID          = S.PRODUCT_ID,
    T.BRANCH_ID           = S.BRANCH_ID,
    T.OFFICER_ID          = S.OFFICER_ID,
    T.LOAN_TYPE           = S.LOAN_TYPE,
    T.LOAN_AMOUNT         = S.LOAN_AMOUNT,
    T.OUTSTANDING_AMOUNT  = S.OUTSTANDING_AMOUNT,
    T.INTEREST_RATE       = S.INTEREST_RATE,
    T.TENURE_MONTHS       = S.TENURE_MONTHS,
    T.START_DATE          = S.START_DATE,
    T.MATURITY_DATE       = S.MATURITY_DATE,
    T.CREDIT_GRADE        = S.CREDIT_GRADE,
    T.LOAN_STATUS         = S.LOAN_STATUS,
    T.STG_UPDATED_AT      = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
    LOAN_ID, LOAN_NUMBER, CUSTOMER_ID, PRODUCT_ID, BRANCH_ID, OFFICER_ID,
    LOAN_TYPE, LOAN_AMOUNT, OUTSTANDING_AMOUNT, INTEREST_RATE,
    TENURE_MONTHS, START_DATE, MATURITY_DATE, CREDIT_GRADE, LOAN_STATUS
)
VALUES
(
    S.LOAN_ID, S.LOAN_NUMBER, S.CUSTOMER_ID, S.PRODUCT_ID, S.BRANCH_ID, S.OFFICER_ID,
    S.LOAN_TYPE, S.LOAN_AMOUNT, S.OUTSTANDING_AMOUNT, S.INTEREST_RATE,
    S.TENURE_MONTHS, S.START_DATE, S.MATURITY_DATE, S.CREDIT_GRADE, S.LOAN_STATUS
);

SELECT
    (SELECT COUNT(*) FROM RAW.BANKING.LOAN) AS RAW_ROWS,
    (SELECT COUNT(*) FROM ANALYTICS.STAGING.STG_LOAN) AS STAGING_ROWS;
