/*==============================================================================
  AVIDIA BANKING DATA GOVERNANCE
  File: transformations/staging/10_merge_loan_collateral.sql

  Purpose:
      Standardize RAW.BANKING.LOAN_COLLATERAL and MERGE it into
      STG_LOAN_COLLATERAL.

  Data-quality boundary:
      - COLLATERAL_ID must be present.
      - No loan-FK or valuation business-validity filtering.
==============================================================================*/

USE ROLE DATA_ENGINEER;
USE WAREHOUSE WH_GOVERNANCE_XS;

MERGE INTO ANALYTICS.STAGING.STG_LOAN_COLLATERAL T
USING
(
    SELECT
        TRIM(COLLATERAL_ID)                         AS COLLATERAL_ID,
        NULLIF(TRIM(LOAN_ID), '')                  AS LOAN_ID,
        NULLIF(UPPER(TRIM(COLLATERAL_TYPE)), '')   AS COLLATERAL_TYPE,
        NULLIF(TRIM(DESCRIPTION), '')              AS DESCRIPTION,
        VALUATION_AMOUNT,
        VALUATION_DATE,
        NULLIF(TRIM(OWNER_NAME), '')               AS OWNER_NAME,
        NULLIF(UPPER(TRIM(COLLATERAL_STATUS)), '') AS COLLATERAL_STATUS
    FROM RAW.BANKING.LOAN_COLLATERAL
    WHERE COLLATERAL_ID IS NOT NULL
      AND TRIM(COLLATERAL_ID) <> ''
) S
ON T.COLLATERAL_ID = S.COLLATERAL_ID

WHEN MATCHED
AND HASH(
        T.LOAN_ID, T.COLLATERAL_TYPE, T.DESCRIPTION,
        T.VALUATION_AMOUNT, T.VALUATION_DATE,
        T.OWNER_NAME, T.COLLATERAL_STATUS
    )
    <>
    HASH(
        S.LOAN_ID, S.COLLATERAL_TYPE, S.DESCRIPTION,
        S.VALUATION_AMOUNT, S.VALUATION_DATE,
        S.OWNER_NAME, S.COLLATERAL_STATUS
    )
THEN UPDATE SET
    T.LOAN_ID             = S.LOAN_ID,
    T.COLLATERAL_TYPE     = S.COLLATERAL_TYPE,
    T.DESCRIPTION         = S.DESCRIPTION,
    T.VALUATION_AMOUNT    = S.VALUATION_AMOUNT,
    T.VALUATION_DATE      = S.VALUATION_DATE,
    T.OWNER_NAME          = S.OWNER_NAME,
    T.COLLATERAL_STATUS   = S.COLLATERAL_STATUS,
    T.STG_UPDATED_AT      = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
    COLLATERAL_ID, LOAN_ID, COLLATERAL_TYPE, DESCRIPTION,
    VALUATION_AMOUNT, VALUATION_DATE, OWNER_NAME, COLLATERAL_STATUS
)
VALUES
(
    S.COLLATERAL_ID, S.LOAN_ID, S.COLLATERAL_TYPE, S.DESCRIPTION,
    S.VALUATION_AMOUNT, S.VALUATION_DATE, S.OWNER_NAME, S.COLLATERAL_STATUS
);

SELECT
    (SELECT COUNT(*) FROM RAW.BANKING.LOAN_COLLATERAL) AS RAW_ROWS,
    (SELECT COUNT(*) FROM ANALYTICS.STAGING.STG_LOAN_COLLATERAL) AS STAGING_ROWS;
