/*==============================================================================
  AVIDIA BANKING DATA GOVERNANCE
  File: transformations/staging/12_merge_product.sql

  Purpose:
      Standardize RAW.BANKING.PRODUCT and MERGE it into STG_PRODUCT.

  Data-quality boundary:
      - PRODUCT_ID must be present.
      - Duplicate PRODUCT_ID is validated before this script.
      - No business-validity filtering is performed.
==============================================================================*/

USE ROLE DATA_ENGINEER;
USE WAREHOUSE WH_GOVERNANCE_XS;

MERGE INTO ANALYTICS.STAGING.STG_PRODUCT T
USING
(
    SELECT
        TRIM(PRODUCT_ID)                        AS PRODUCT_ID,
        NULLIF(TRIM(PRODUCT_CODE), '')          AS PRODUCT_CODE,
        NULLIF(TRIM(PRODUCT_NAME), '')          AS PRODUCT_NAME,
        NULLIF(UPPER(TRIM(PRODUCT_TYPE)), '')   AS PRODUCT_TYPE,
        NULLIF(UPPER(TRIM(CURRENCY)), '')       AS CURRENCY,
        INTEREST_RATE,
        MIN_BALANCE,
        NULLIF(UPPER(TRIM(PRODUCT_STATUS)), '') AS PRODUCT_STATUS
    FROM RAW.BANKING.PRODUCT
    WHERE PRODUCT_ID IS NOT NULL
      AND TRIM(PRODUCT_ID) <> ''
) S
ON T.PRODUCT_ID = S.PRODUCT_ID

WHEN MATCHED
AND HASH(
        T.PRODUCT_CODE, T.PRODUCT_NAME, T.PRODUCT_TYPE,
        T.CURRENCY, T.INTEREST_RATE, T.MIN_BALANCE, T.PRODUCT_STATUS
    )
    <>
    HASH(
        S.PRODUCT_CODE, S.PRODUCT_NAME, S.PRODUCT_TYPE,
        S.CURRENCY, S.INTEREST_RATE, S.MIN_BALANCE, S.PRODUCT_STATUS
    )
THEN UPDATE SET
    T.PRODUCT_CODE    = S.PRODUCT_CODE,
    T.PRODUCT_NAME    = S.PRODUCT_NAME,
    T.PRODUCT_TYPE    = S.PRODUCT_TYPE,
    T.CURRENCY        = S.CURRENCY,
    T.INTEREST_RATE   = S.INTEREST_RATE,
    T.MIN_BALANCE     = S.MIN_BALANCE,
    T.PRODUCT_STATUS  = S.PRODUCT_STATUS,
    T.STG_UPDATED_AT  = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
    PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_TYPE,
    CURRENCY, INTEREST_RATE, MIN_BALANCE, PRODUCT_STATUS
)
VALUES
(
    S.PRODUCT_ID, S.PRODUCT_CODE, S.PRODUCT_NAME, S.PRODUCT_TYPE,
    S.CURRENCY, S.INTEREST_RATE, S.MIN_BALANCE, S.PRODUCT_STATUS
);

SELECT
    (SELECT COUNT(*) FROM RAW.BANKING.PRODUCT) AS RAW_ROWS,
    (SELECT COUNT(*) FROM ANALYTICS.STAGING.STG_PRODUCT) AS STAGING_ROWS;
