/*==============================================================================
  AVIDIA BANKING DATA GOVERNANCE
  File: transformations/staging/13_merge_transactions.sql

  Purpose:
      Standardize RAW.BANKING.TRANSACTIONS and MERGE it into STG_TRANSACTIONS.

  Important:
      REFERENCE and MEMO are deliberately preserved without semantic cleanup
      because they contain misleading sensitive values used by classification.

  Data-quality boundary:
      - TRANSACTION_ID must be present.
      - No account/customer FK validation.
      - No DEBIT_CREDIT/status validity filtering.
      - No timeliness or amount-quality filtering.
==============================================================================*/

USE ROLE DATA_ENGINEER;
USE WAREHOUSE WH_GOVERNANCE_XS;

MERGE INTO ANALYTICS.STAGING.STG_TRANSACTIONS T
USING
(
    SELECT
        TRIM(TRANSACTION_ID)                        AS TRANSACTION_ID,
        NULLIF(TRIM(ACCOUNT_ID), '')                AS ACCOUNT_ID,
        NULLIF(TRIM(CUSTOMER_ID), '')               AS CUSTOMER_ID,
        TRANSACTION_DATE,
        POSTING_DATE,
        NULLIF(UPPER(TRIM(TRANSACTION_TYPE)), '')   AS TRANSACTION_TYPE,
        NULLIF(UPPER(TRIM(TRANSACTION_CODE)), '')   AS TRANSACTION_CODE,
        AMOUNT,
        NULLIF(UPPER(TRIM(CURRENCY)), '')           AS CURRENCY,
        NULLIF(UPPER(TRIM(DEBIT_CREDIT)), '')       AS DEBIT_CREDIT,
        NULLIF(UPPER(TRIM(CHANNEL)), '')            AS CHANNEL,
        NULLIF(TRIM(MERCHANT_NAME), '')             AS MERCHANT_NAME,
        NULLIF(UPPER(TRIM(STATUS)), '')             AS STATUS,

        REFERENCE,
        MEMO,

        BALANCE_AFTER_TRANSACTION,
        LOAD_TIMESTAMP,
        NULLIF(TRIM(TRANSACTION_GROUP_ID), '')      AS TRANSACTION_GROUP_ID
    FROM RAW.BANKING.TRANSACTIONS
    WHERE TRANSACTION_ID IS NOT NULL
      AND TRIM(TRANSACTION_ID) <> ''
) S
ON T.TRANSACTION_ID = S.TRANSACTION_ID

WHEN MATCHED
AND HASH(
        T.ACCOUNT_ID, T.CUSTOMER_ID,
        T.TRANSACTION_DATE, T.POSTING_DATE,
        T.TRANSACTION_TYPE, T.TRANSACTION_CODE,
        T.AMOUNT, T.CURRENCY, T.DEBIT_CREDIT,
        T.CHANNEL, T.MERCHANT_NAME, T.STATUS,
        T.REFERENCE, T.MEMO, T.BALANCE_AFTER_TRANSACTION,
        T.LOAD_TIMESTAMP, T.TRANSACTION_GROUP_ID
    )
    <>
    HASH(
        S.ACCOUNT_ID, S.CUSTOMER_ID,
        S.TRANSACTION_DATE, S.POSTING_DATE,
        S.TRANSACTION_TYPE, S.TRANSACTION_CODE,
        S.AMOUNT, S.CURRENCY, S.DEBIT_CREDIT,
        S.CHANNEL, S.MERCHANT_NAME, S.STATUS,
        S.REFERENCE, S.MEMO, S.BALANCE_AFTER_TRANSACTION,
        S.LOAD_TIMESTAMP, S.TRANSACTION_GROUP_ID
    )
THEN UPDATE SET
    T.ACCOUNT_ID                  = S.ACCOUNT_ID,
    T.CUSTOMER_ID                 = S.CUSTOMER_ID,
    T.TRANSACTION_DATE            = S.TRANSACTION_DATE,
    T.POSTING_DATE                = S.POSTING_DATE,
    T.TRANSACTION_TYPE            = S.TRANSACTION_TYPE,
    T.TRANSACTION_CODE            = S.TRANSACTION_CODE,
    T.AMOUNT                      = S.AMOUNT,
    T.CURRENCY                    = S.CURRENCY,
    T.DEBIT_CREDIT                = S.DEBIT_CREDIT,
    T.CHANNEL                     = S.CHANNEL,
    T.MERCHANT_NAME               = S.MERCHANT_NAME,
    T.STATUS                      = S.STATUS,
    T.REFERENCE                   = S.REFERENCE,
    T.MEMO                        = S.MEMO,
    T.BALANCE_AFTER_TRANSACTION   = S.BALANCE_AFTER_TRANSACTION,
    T.LOAD_TIMESTAMP              = S.LOAD_TIMESTAMP,
    T.TRANSACTION_GROUP_ID        = S.TRANSACTION_GROUP_ID,
    T.STG_UPDATED_AT              = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
    TRANSACTION_ID, ACCOUNT_ID, CUSTOMER_ID,
    TRANSACTION_DATE, POSTING_DATE,
    TRANSACTION_TYPE, TRANSACTION_CODE,
    AMOUNT, CURRENCY, DEBIT_CREDIT, CHANNEL,
    MERCHANT_NAME, STATUS, REFERENCE, MEMO,
    BALANCE_AFTER_TRANSACTION, LOAD_TIMESTAMP,
    TRANSACTION_GROUP_ID
)
VALUES
(
    S.TRANSACTION_ID, S.ACCOUNT_ID, S.CUSTOMER_ID,
    S.TRANSACTION_DATE, S.POSTING_DATE,
    S.TRANSACTION_TYPE, S.TRANSACTION_CODE,
    S.AMOUNT, S.CURRENCY, S.DEBIT_CREDIT, S.CHANNEL,
    S.MERCHANT_NAME, S.STATUS, S.REFERENCE, S.MEMO,
    S.BALANCE_AFTER_TRANSACTION, S.LOAD_TIMESTAMP,
    S.TRANSACTION_GROUP_ID
);

SELECT
    (SELECT COUNT(*) FROM RAW.BANKING.TRANSACTIONS) AS RAW_ROWS,
    (SELECT COUNT(*) FROM ANALYTICS.STAGING.STG_TRANSACTIONS) AS STAGING_ROWS;
