/*==============================================================================
 AVIDIA BANK - BLOCK 3 DATA QUALITY PERMISSIONS

 Purpose:
   Minimum privileges for Snowflake Data Metric Function based DQ on the
   certified-candidate mart ANALYTICS.MARTS.DEPOSITS_DAILY.

 Notes:
   - DATA_GOVERNANCE_ADMIN creates DQ metadata and persists DQ_RESULT.
   - SVC_PIPELINE_ROLE owns the dbt-created MART, so it attaches DMFs.
   - ACCOUNTADMIN is not a runtime role.
==============================================================================*/

USE ROLE SECURITYADMIN;

-- Governance DQ schema access.
GRANT USAGE
ON DATABASE GOVERNANCE
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE
ON SCHEMA GOVERNANCE.DQ
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT CREATE TABLE
ON SCHEMA GOVERNANCE.DQ
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT CREATE DATA METRIC FUNCTION
ON SCHEMA GOVERNANCE.DQ
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE
ON DATABASE GOVERNANCE
TO ROLE SVC_PIPELINE_ROLE;

GRANT USAGE
ON SCHEMA GOVERNANCE.DQ
TO ROLE SVC_PIPELINE_ROLE;

-- Data access required by system and custom DMFs.
GRANT USAGE
ON DATABASE ANALYTICS
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE
ON SCHEMA ANALYTICS.MARTS
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE
ON SCHEMA ANALYTICS.STAGING
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT SELECT
ON TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT SELECT
ON TABLE ANALYTICS.STAGING.STG_ACCOUNT_DAILY_BALANCE
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT SELECT
ON TABLE ANALYTICS.STAGING.STG_CUSTOMER
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT SELECT
ON TABLE ANALYTICS.STAGING.STG_GL_CONTROL_TOTAL
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE
ON DATABASE ANALYTICS
TO ROLE SVC_PIPELINE_ROLE;

GRANT USAGE
ON SCHEMA ANALYTICS.MARTS
TO ROLE SVC_PIPELINE_ROLE;

GRANT USAGE
ON SCHEMA ANALYTICS.STAGING
TO ROLE SVC_PIPELINE_ROLE;

GRANT SELECT
ON TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
TO ROLE SVC_PIPELINE_ROLE;

GRANT SELECT
ON TABLE ANALYTICS.STAGING.STG_ACCOUNT_DAILY_BALANCE
TO ROLE SVC_PIPELINE_ROLE;

GRANT SELECT
ON TABLE ANALYTICS.STAGING.STG_CUSTOMER
TO ROLE SVC_PIPELINE_ROLE;

GRANT SELECT
ON TABLE ANALYTICS.STAGING.STG_GL_CONTROL_TOTAL
TO ROLE SVC_PIPELINE_ROLE;

-- Required to associate and evaluate DMFs.
GRANT EXECUTE DATA METRIC FUNCTION
ON ACCOUNT
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT EXECUTE DATA METRIC FUNCTION
ON ACCOUNT
TO ROLE SVC_PIPELINE_ROLE;

-- System DMF visibility and native DQ monitoring evidence.
GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER
TO ROLE SVC_PIPELINE_ROLE;

GRANT APPLICATION ROLE SNOWFLAKE.DATA_QUALITY_MONITORING_VIEWER
TO ROLE DATA_GOVERNANCE_ADMIN;

-- Future custom DMFs created in GOVERNANCE.DQ should be executable by the
-- mart owner role and governance role. 02_create_custom_dmfs.sql also grants
-- current functions explicitly after creation.
GRANT USAGE
ON FUTURE DATA METRIC FUNCTIONS IN SCHEMA GOVERNANCE.DQ
TO ROLE DATA_GOVERNANCE_ADMIN;

GRANT USAGE
ON FUTURE DATA METRIC FUNCTIONS IN SCHEMA GOVERNANCE.DQ
TO ROLE SVC_PIPELINE_ROLE;

SHOW GRANTS TO ROLE DATA_GOVERNANCE_ADMIN;
SHOW GRANTS TO ROLE SVC_PIPELINE_ROLE;
