/*==============================================================================
 AVIDIA BANK - ATTACH DQ CHECKS TO DEPOSITS_DAILY

 Purpose:
   Associate exactly six data-quality checks with the certified-candidate mart:
   four Snowflake system DMFs and two custom banking DMFs.

 Notes:
   - DEPOSITS_DAILY is owned by SVC_PIPELINE_ROLE, so that role performs
     ALTER TABLE.
   - Each DMF returns a violation count where 0 means PASS.
   - Every association has EXPECTATION ... (VALUE = 0).
   - The script runs as SVC_PIPELINE_ROLE, so DMFs run with the mart owner
     context without needing an explicit EXECUTE AS ROLE clause.
==============================================================================*/

USE ROLE SVC_PIPELINE_ROLE;
USE WAREHOUSE WH_GOVERNANCE_XS;

ALTER TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
    SET DATA_METRIC_SCHEDULE = '1440 MINUTE';

-- Remove existing Block 3 associations if this script is re-run. Snowflake
-- does not support IF EXISTS for association drops, so each drop is isolated.
EXECUTE IMMEDIATE $$
BEGIN
    ALTER TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
        DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
        ON (ACCOUNT_ID);
EXCEPTION
    WHEN STATEMENT_ERROR THEN NULL;
END;
$$;

EXECUTE IMMEDIATE $$
BEGIN
    ALTER TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
        DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT
        ON (ACCOUNT_ID, BUSINESS_DATE);
EXCEPTION
    WHEN STATEMENT_ERROR THEN NULL;
END;
$$;

EXECUTE IMMEDIATE $$
BEGIN
    ALTER TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
        DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES
        ON (ACCOUNT_STATUS);
EXCEPTION
    WHEN STATEMENT_ERROR THEN NULL;
END;
$$;

EXECUTE IMMEDIATE $$
BEGIN
    ALTER TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
        DROP DATA METRIC FUNCTION SNOWFLAKE.CORE.REFERENTIAL_INTEGRITY_COUNT
        ON
        (
            CUSTOMER_ID,
            TABLE(ANALYTICS.STAGING.STG_CUSTOMER(CUSTOMER_ID))
        );
EXCEPTION
    WHEN STATEMENT_ERROR THEN NULL;
END;
$$;

EXECUTE IMMEDIATE $$
BEGIN
    ALTER TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
        DROP DATA METRIC FUNCTION GOVERNANCE.DQ.DMF_LATEST_BUSINESS_DATE_MATCH
        ON
        (
            BUSINESS_DATE,
            TABLE(ANALYTICS.STAGING.STG_ACCOUNT_DAILY_BALANCE(BUSINESS_DATE))
        );
EXCEPTION
    WHEN STATEMENT_ERROR THEN NULL;
END;
$$;

EXECUTE IMMEDIATE $$
BEGIN
    ALTER TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
        DROP DATA METRIC FUNCTION GOVERNANCE.DQ.DMF_GL_DEPOSIT_RECONCILIATION
        ON
        (
            BUSINESS_DATE,
            CLOSING_BALANCE,
            TABLE
            (
                ANALYTICS.STAGING.STG_GL_CONTROL_TOTAL
                (
                    BUSINESS_DATE,
                    PRODUCT_TYPE,
                    CONTROL_TOTAL
                )
            )
        );
EXCEPTION
    WHEN STATEMENT_ERROR THEN NULL;
END;
$$;

ALTER TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
        ON (ACCOUNT_ID)
        EXPECTATION COMPLETENESS_CDE_NOT_NULL (VALUE = 0);

ALTER TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT
        ON (ACCOUNT_ID, BUSINESS_DATE)
        EXPECTATION UNIQUENESS_BUSINESS_KEY (VALUE = 0);

ALTER TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES
        ON
        (
            ACCOUNT_STATUS,
            ACCOUNT_STATUS -> ACCOUNT_STATUS IN ('ACTIVE', 'CLOSED', 'DORMANT')
        )
        EXPECTATION VALIDITY_ACCOUNT_STATUS (VALUE = 0);

ALTER TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.REFERENTIAL_INTEGRITY_COUNT
        ON
        (
            CUSTOMER_ID,
            TABLE(ANALYTICS.STAGING.STG_CUSTOMER(CUSTOMER_ID))
        )
        EXPECTATION CONSISTENCY_ACCOUNT_CUSTOMER (VALUE = 0);

ALTER TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
    ADD DATA METRIC FUNCTION GOVERNANCE.DQ.DMF_LATEST_BUSINESS_DATE_MATCH
        ON
        (
            BUSINESS_DATE,
            TABLE(ANALYTICS.STAGING.STG_ACCOUNT_DAILY_BALANCE(BUSINESS_DATE))
        )
        EXPECTATION TIMELINESS_LATEST_BUSINESS_DATE (VALUE = 0);

ALTER TABLE ANALYTICS.MARTS.DEPOSITS_DAILY
    ADD DATA METRIC FUNCTION GOVERNANCE.DQ.DMF_GL_DEPOSIT_RECONCILIATION
        ON
        (
            BUSINESS_DATE,
            CLOSING_BALANCE,
            TABLE
            (
                ANALYTICS.STAGING.STG_GL_CONTROL_TOTAL
                (
                    BUSINESS_DATE,
                    PRODUCT_TYPE,
                    CONTROL_TOTAL
                )
            )
        )
        EXPECTATION ACCURACY_GL_RECONCILIATION (VALUE = 0);

SELECT
    METRIC_DATABASE_NAME,
    METRIC_SCHEMA_NAME,
    METRIC_NAME,
    REF_ENTITY_DATABASE_NAME,
    REF_ENTITY_SCHEMA_NAME,
    REF_ENTITY_NAME,
    REF_ARGUMENTS,
    SCHEDULE,
    USE_ROLE
FROM TABLE
(
    ANALYTICS.INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES
    (
        REF_ENTITY_NAME => 'ANALYTICS.MARTS.DEPOSITS_DAILY',
        REF_ENTITY_DOMAIN => 'TABLE'
    )
)
ORDER BY
    METRIC_DATABASE_NAME,
    METRIC_SCHEMA_NAME,
    METRIC_NAME;
