/*==============================================================================
 AVIDIA BANK - RUN AND PERSIST DQ RESULTS

 Purpose:
   Execute all DEPOSITS_DAILY DMF expectations immediately, persist the native
   Snowflake DQ history, and copy exactly six governance result rows into
   GOVERNANCE.DQ.DQ_RESULT.
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;
USE DATABASE GOVERNANCE;
USE SCHEMA DQ;

CREATE OR REPLACE TEMP TABLE TMP_DQ_RUN_CONTEXT
(
    RUN_ID VARCHAR(36)
);

INSERT INTO TMP_DQ_RUN_CONTEXT (RUN_ID)
SELECT UUID_STRING();

CALL SYSTEM$EVALUATE_DATA_QUALITY_EXPECTATIONS_PERSIST_RESULT
(
    'ANALYTICS.MARTS.DEPOSITS_DAILY',
    TRUE
);

INSERT INTO GOVERNANCE.DQ.DQ_RESULT
(
    RUN_ID,
    CHECK_NAME,
    QUALITY_DIMENSION,
    OBJECT_FQN,
    METRIC_DATABASE,
    METRIC_SCHEMA,
    METRIC_NAME,
    ARGUMENTS,
    METRIC_VALUE,
    THRESHOLD_VALUE,
    STATUS,
    EXPECTATION_EXPRESSION,
    MEASURED_AT
)
WITH EXPECTATION_DIMENSIONS AS
(
    SELECT * FROM VALUES
        ('COMPLETENESS_CDE_NOT_NULL',        'COMPLETENESS'),
        ('UNIQUENESS_BUSINESS_KEY',          'UNIQUENESS'),
        ('VALIDITY_ACCOUNT_STATUS',          'VALIDITY'),
        ('CONSISTENCY_ACCOUNT_CUSTOMER',     'CONSISTENCY'),
        ('TIMELINESS_LATEST_BUSINESS_DATE',  'TIMELINESS'),
        ('ACCURACY_GL_RECONCILIATION',       'ACCURACY')
        AS V(CHECK_NAME, QUALITY_DIMENSION)
)
SELECT
    C.RUN_ID,
    R.EXPECTATION_NAME AS CHECK_NAME,
    D.QUALITY_DIMENSION,
    'ANALYTICS.MARTS.DEPOSITS_DAILY' AS OBJECT_FQN,
    R.METRIC_DATABASE,
    R.METRIC_SCHEMA,
    R.METRIC_NAME,
    R.ARGUMENTS,
    TRY_TO_DECIMAL(R.VALUE::VARCHAR, 38, 6) AS METRIC_VALUE,
    0 AS THRESHOLD_VALUE,
    IFF(LOWER(R.EXPECTATION_VIOLATED::VARCHAR) = 'false', 'PASS', 'FAIL')
        AS STATUS,
    R.EXPECTATION_EXPRESSION,
    CURRENT_TIMESTAMP() AS MEASURED_AT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) AS R
CROSS JOIN TMP_DQ_RUN_CONTEXT AS C
INNER JOIN EXPECTATION_DIMENSIONS AS D
    ON R.EXPECTATION_NAME = D.CHECK_NAME
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY R.EXPECTATION_NAME
    ORDER BY R.EXPECTATION_ID
) = 1;

SELECT
    RUN_ID,
    CHECK_NAME,
    QUALITY_DIMENSION,
    METRIC_NAME,
    METRIC_VALUE,
    THRESHOLD_VALUE,
    STATUS,
    MEASURED_AT
FROM GOVERNANCE.DQ.DQ_RESULT
WHERE RUN_ID = (SELECT RUN_ID FROM TMP_DQ_RUN_CONTEXT)
ORDER BY QUALITY_DIMENSION;
