!source setup/01_roles.sql
!source setup/02_warehouse.sql
!source setup/03_databases_schemas.sql
!source setup/04_base_grants.sql
!source setup/05_raw_tables.sql
--!source setup/03_databases_schemas.sql
--!source setup/04_file_format_stage.sql
--!source setup/05_raw_tables.sql
--!source setup/06_setup_validation.sql