/*==============================================================================
 AVIDIA BANK - STREAMLIT CATALOG VIEW

 Purpose:
   Create one app-ready data dictionary view for the existing Streamlit app.

 Grain:
   One row per MART object + column.

 Sources:
   - ANALYTICS.INFORMATION_SCHEMA.TABLES / COLUMNS for live object metadata
   - Snowflake tag references for owner/steward/certification/CDE/classification
   - GOVERNANCE.CATALOG.LINEAGE_EDGE for latest upstream lineage snapshot
   - GOVERNANCE.DQ.DQ_RESULT for latest DQ outcome
   - SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY / QUERY_HISTORY for usage evidence
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

CREATE OR REPLACE VIEW GOVERNANCE.CATALOG.V_STREAMLIT_CATALOG
COMMENT = 'One-row-per-MART-column catalog surface used by the Avidia Data Catalog Streamlit app.'
AS
WITH MART_OBJECTS AS
(
    SELECT
        TABLE_CATALOG AS DATABASE_NAME,
        TABLE_SCHEMA AS SCHEMA_NAME,
        TABLE_NAME AS OBJECT_NAME,
        CASE
            WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE'
            ELSE TABLE_TYPE
        END AS OBJECT_TYPE,
        TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME AS OBJECT_FQN,
        COMMENT AS OBJECT_DESCRIPTION,
        CREATED AS CREATED_AT,
        LAST_ALTERED AS LAST_REFRESH
    FROM ANALYTICS.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'MARTS'
      AND TABLE_NAME IN
      (
          'CUSTOMER_360',
          'DEPOSITS_DAILY',
          'LOAN_PORTFOLIO'
      )
),

MART_COLUMNS AS
(
    SELECT
        TABLE_CATALOG AS DATABASE_NAME,
        TABLE_SCHEMA AS SCHEMA_NAME,
        TABLE_NAME AS OBJECT_NAME,
        TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME AS OBJECT_FQN,
        COLUMN_NAME,
        ORDINAL_POSITION,
        DATA_TYPE,
        COMMENT AS COLUMN_DESCRIPTION
    FROM ANALYTICS.INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'MARTS'
      AND TABLE_NAME IN
      (
          'CUSTOMER_360',
          'DEPOSITS_DAILY',
          'LOAN_PORTFOLIO'
      )
),

NATIVE_OBJECT_TAGS AS
(
    SELECT
        'ANALYTICS.MARTS.CUSTOMER_360' AS OBJECT_FQN,
        TAG_NAME,
        TAG_VALUE,
        100 AS SOURCE_PRIORITY,
        CURRENT_TIMESTAMP() AS SOURCE_UPDATED_AT
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.TAG_REFERENCES
        (
            'ANALYTICS.MARTS.CUSTOMER_360',
            'TABLE'
        )
    )

    UNION ALL

    SELECT
        'ANALYTICS.MARTS.DEPOSITS_DAILY' AS OBJECT_FQN,
        TAG_NAME,
        TAG_VALUE,
        100 AS SOURCE_PRIORITY,
        CURRENT_TIMESTAMP() AS SOURCE_UPDATED_AT
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.TAG_REFERENCES
        (
            'ANALYTICS.MARTS.DEPOSITS_DAILY',
            'TABLE'
        )
    )

    UNION ALL

    SELECT
        'ANALYTICS.MARTS.LOAN_PORTFOLIO' AS OBJECT_FQN,
        TAG_NAME,
        TAG_VALUE,
        100 AS SOURCE_PRIORITY,
        CURRENT_TIMESTAMP() AS SOURCE_UPDATED_AT
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.TAG_REFERENCES
        (
            'ANALYTICS.MARTS.LOAN_PORTFOLIO',
            'TABLE'
        )
    )
),

DESIRED_OBJECT_TAGS AS
(
    SELECT
        O.OBJECT_FQN,
        T.TAG_NAME,
        T.TAG_VALUE,
        CASE
            WHEN T.OBJECT_LEVEL IN ('TABLE', 'VIEW') THEN 90
            ELSE 80
        END AS SOURCE_PRIORITY,
        T.UPDATED_AT AS SOURCE_UPDATED_AT
    FROM MART_OBJECTS AS O
    INNER JOIN GOVERNANCE.CATALOG.TAG_ASSIGNMENT AS T
        ON T.ACTIVE_FLAG = TRUE
       AND T.DATABASE_NAME = O.DATABASE_NAME
       AND T.TAG_NAME IN
       (
           'DATA_OWNER',
           'DATA_STEWARD',
           'CERTIFICATION',
           'DOMAIN'
       )
       AND
       (
            (
                T.OBJECT_LEVEL IN ('TABLE', 'VIEW')
                AND T.SCHEMA_NAME = O.SCHEMA_NAME
                AND T.OBJECT_NAME = O.OBJECT_NAME
            )
         OR (
                T.OBJECT_LEVEL = 'SCHEMA'
                AND T.SCHEMA_NAME = O.SCHEMA_NAME
                AND T.OBJECT_NAME IS NULL
            )
       )
),

CERTIFICATION_LOG_OBJECT_TAGS AS
(
    SELECT
        OBJECT_FQN,
        'CERTIFICATION' AS TAG_NAME,
        'CERTIFIED' AS TAG_VALUE,
        85 AS SOURCE_PRIORITY,
        COALESCE(CERTIFIED_AT, REQUESTED_AT) AS SOURCE_UPDATED_AT
    FROM GOVERNANCE.EVIDENCE.CERTIFICATION_LOG
    WHERE OUTCOME = 'CERTIFIED'
      AND OBJECT_FQN IN
      (
          'ANALYTICS.MARTS.CUSTOMER_360',
          'ANALYTICS.MARTS.DEPOSITS_DAILY',
          'ANALYTICS.MARTS.LOAN_PORTFOLIO'
      )
    QUALIFY ROW_NUMBER() OVER
    (
        PARTITION BY OBJECT_FQN
        ORDER BY COALESCE(CERTIFIED_AT, REQUESTED_AT) DESC,
                 CERTIFICATION_RUN_ID DESC
    ) = 1
),

OBJECT_TAGS AS
(
    SELECT
        OBJECT_FQN,
        TAG_NAME,
        TAG_VALUE
    FROM
    (
        SELECT * FROM NATIVE_OBJECT_TAGS
        UNION ALL
        SELECT * FROM DESIRED_OBJECT_TAGS
        UNION ALL
        SELECT * FROM CERTIFICATION_LOG_OBJECT_TAGS
    )
    QUALIFY ROW_NUMBER() OVER
    (
        PARTITION BY OBJECT_FQN, TAG_NAME
        ORDER BY SOURCE_PRIORITY DESC, SOURCE_UPDATED_AT DESC
    ) = 1
),

OBJECT_TAG_PIVOT AS
(
    SELECT
        OBJECT_FQN,
        MAX(IFF(TAG_NAME = 'DATA_OWNER', TAG_VALUE, NULL)) AS DATA_OWNER,
        MAX(IFF(TAG_NAME = 'DATA_STEWARD', TAG_VALUE, NULL)) AS DATA_STEWARD,
        MAX(IFF(TAG_NAME = 'CERTIFICATION', TAG_VALUE, NULL)) AS CERTIFICATION,
        MAX(IFF(TAG_NAME = 'DOMAIN', TAG_VALUE, NULL)) AS DOMAIN
    FROM OBJECT_TAGS
    GROUP BY OBJECT_FQN
),

NATIVE_COLUMN_TAGS AS
(
    SELECT
        'ANALYTICS.MARTS.CUSTOMER_360' AS OBJECT_FQN,
        COLUMN_NAME,
        TAG_NAME,
        TAG_VALUE,
        100 AS SOURCE_PRIORITY,
        CURRENT_TIMESTAMP() AS SOURCE_UPDATED_AT
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS
        (
            'ANALYTICS.MARTS.CUSTOMER_360',
            'TABLE'
        )
    )

    UNION ALL

    SELECT
        'ANALYTICS.MARTS.DEPOSITS_DAILY' AS OBJECT_FQN,
        COLUMN_NAME,
        TAG_NAME,
        TAG_VALUE,
        100 AS SOURCE_PRIORITY,
        CURRENT_TIMESTAMP() AS SOURCE_UPDATED_AT
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS
        (
            'ANALYTICS.MARTS.DEPOSITS_DAILY',
            'TABLE'
        )
    )

    UNION ALL

    SELECT
        'ANALYTICS.MARTS.LOAN_PORTFOLIO' AS OBJECT_FQN,
        COLUMN_NAME,
        TAG_NAME,
        TAG_VALUE,
        100 AS SOURCE_PRIORITY,
        CURRENT_TIMESTAMP() AS SOURCE_UPDATED_AT
    FROM TABLE
    (
        ANALYTICS.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS
        (
            'ANALYTICS.MARTS.LOAN_PORTFOLIO',
            'TABLE'
        )
    )
),

DESIRED_COLUMN_TAGS AS
(
    SELECT
        C.OBJECT_FQN,
        C.COLUMN_NAME,
        T.TAG_NAME,
        T.TAG_VALUE,
        90 AS SOURCE_PRIORITY,
        T.UPDATED_AT AS SOURCE_UPDATED_AT
    FROM MART_COLUMNS AS C
    INNER JOIN GOVERNANCE.CATALOG.TAG_ASSIGNMENT AS T
        ON T.ACTIVE_FLAG = TRUE
       AND T.DATABASE_NAME = C.DATABASE_NAME
       AND T.SCHEMA_NAME = C.SCHEMA_NAME
       AND T.OBJECT_NAME = C.OBJECT_NAME
       AND T.COLUMN_NAME = C.COLUMN_NAME
       AND T.OBJECT_LEVEL = 'COLUMN'
       AND T.TAG_NAME IN
       (
           'CDE',
           'CLASSIFICATION'
       )
),

REGISTRY_CDE_COLUMN_TAGS AS
(
    SELECT
        C.OBJECT_FQN,
        C.COLUMN_NAME,
        'CDE' AS TAG_NAME,
        MIN(R.CDE_TIER) AS TAG_VALUE,
        70 AS SOURCE_PRIORITY,
        CURRENT_TIMESTAMP() AS SOURCE_UPDATED_AT
    FROM MART_COLUMNS AS C
    INNER JOIN OBJECT_TAG_PIVOT AS OTP
        ON OTP.OBJECT_FQN = C.OBJECT_FQN
    INNER JOIN GOVERNANCE.CATALOG.CDE_REGISTRY AS R
        ON R.ACTIVE_FLAG = TRUE
       AND R.DATA_DOMAIN = OTP.DOMAIN
       AND R.COLUMN_NAME = C.COLUMN_NAME
    GROUP BY
        C.OBJECT_FQN,
        C.COLUMN_NAME
),

COLUMN_TAGS AS
(
    SELECT
        OBJECT_FQN,
        COLUMN_NAME,
        TAG_NAME,
        TAG_VALUE
    FROM
    (
        SELECT * FROM NATIVE_COLUMN_TAGS
        UNION ALL
        SELECT * FROM DESIRED_COLUMN_TAGS
        UNION ALL
        SELECT * FROM REGISTRY_CDE_COLUMN_TAGS
    )
    QUALIFY ROW_NUMBER() OVER
    (
        PARTITION BY OBJECT_FQN, COLUMN_NAME, TAG_NAME
        ORDER BY SOURCE_PRIORITY DESC, SOURCE_UPDATED_AT DESC
    ) = 1
),

COLUMN_TAG_PIVOT AS
(
    SELECT
        OBJECT_FQN,
        COLUMN_NAME,
        MAX(IFF(TAG_NAME = 'CDE', TAG_VALUE, NULL)) AS CDE_TIER,
        MAX(IFF(TAG_NAME = 'CLASSIFICATION', TAG_VALUE, NULL)) AS CLASSIFICATION
    FROM COLUMN_TAGS
    GROUP BY
        OBJECT_FQN,
        COLUMN_NAME
),

LATEST_LINEAGE AS
(
    SELECT *
    FROM GOVERNANCE.CATALOG.LINEAGE_EDGE
    QUALIFY DENSE_RANK() OVER
    (
        PARTITION BY ROOT_OBJECT
        ORDER BY SNAPSHOT_AT DESC
    ) = 1
),

UPSTREAM_SOURCES AS
(
    SELECT
        ROOT_OBJECT AS OBJECT_FQN,
        LISTAGG(DISTINCT SOURCE_OBJECT, ', ')
            WITHIN GROUP (ORDER BY SOURCE_OBJECT) AS UPSTREAM_SOURCES
    FROM LATEST_LINEAGE
    WHERE DIRECTION = 'UPSTREAM'
      AND SOURCE_OBJECT_DOMAIN = 'TABLE'
      AND SOURCE_OBJECT IS NOT NULL
    GROUP BY ROOT_OBJECT
),

LATEST_DQ_RUN AS
(
    SELECT *
    FROM GOVERNANCE.DQ.DQ_RESULT
    QUALIFY DENSE_RANK() OVER
    (
        PARTITION BY OBJECT_FQN
        ORDER BY MEASURED_AT DESC, RUN_ID DESC
    ) = 1
),

DQ_SUMMARY AS
(
    SELECT
        OBJECT_FQN,
        CASE
            WHEN COUNT(*) = 0 THEN 'NO_DQ'
            WHEN COUNT(*) = 6
             AND COUNT(DISTINCT QUALITY_DIMENSION) = 6
             AND COUNT_IF(STATUS = 'PASS') = 6 THEN 'PASS'
            ELSE 'FAIL'
        END AS QUALITY_RESULT,
        MAX(MEASURED_AT) AS QUALITY_MEASURED_AT
    FROM LATEST_DQ_RUN
    GROUP BY OBJECT_FQN
),

USAGE_SUMMARY AS
(
    SELECT
        O.OBJECT_FQN,
        COUNT(DISTINCT AH.QUERY_ID) AS QUERY_COUNT_SINCE_CREATION,
        COUNT(DISTINCT QH.ROLE_NAME) AS DISTINCT_ROLES_SINCE_CREATION
    FROM MART_OBJECTS AS O
    LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY AS AH
        ON AH.QUERY_START_TIME >= O.CREATED_AT
       AND
       (
            AH.DIRECT_OBJECTS_ACCESSED::VARCHAR ILIKE '%' || O.OBJECT_FQN || '%'
         OR AH.BASE_OBJECTS_ACCESSED::VARCHAR ILIKE '%' || O.OBJECT_FQN || '%'
         OR AH.OBJECTS_MODIFIED::VARCHAR ILIKE '%' || O.OBJECT_FQN || '%'
       )
    LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY AS QH
        ON QH.QUERY_ID = AH.QUERY_ID
    GROUP BY O.OBJECT_FQN
)

SELECT
    O.DATABASE_NAME,
    O.SCHEMA_NAME,
    O.OBJECT_NAME,
    O.OBJECT_TYPE,
    O.OBJECT_FQN,
    C.COLUMN_NAME,
    C.DATA_TYPE,
    COALESCE(C.COLUMN_DESCRIPTION, 'NOT AVAILABLE') AS DESCRIPTION,
    COALESCE(O.OBJECT_DESCRIPTION, 'NOT AVAILABLE') AS OBJECT_DESCRIPTION,
    COALESCE(OTP.DOMAIN, 'NOT AVAILABLE') AS DOMAIN,
    COALESCE(OTP.DATA_OWNER, 'NOT AVAILABLE') AS DATA_OWNER,
    COALESCE(OTP.DATA_STEWARD, 'NOT AVAILABLE') AS DATA_STEWARD,
    COALESCE(OTP.CERTIFICATION, 'NOT CERTIFIED') AS CERTIFICATION,
    IFF(CTP.CDE_TIER IS NULL, 'NO', 'YES') AS CDE_FLAG,
    COALESCE(CTP.CDE_TIER, 'NOT A CDE') AS CDE_TIER,
    COALESCE(CTP.CLASSIFICATION, 'NOT CLASSIFIED') AS CLASSIFICATION,
    COALESCE(US.UPSTREAM_SOURCES, 'NOT AVAILABLE') AS UPSTREAM_SOURCES,
    O.LAST_REFRESH,
    COALESCE(DQ.QUALITY_RESULT, 'NO_DQ') AS QUALITY_RESULT,
    DQ.QUALITY_MEASURED_AT,
    COALESCE(UG.QUERY_COUNT_SINCE_CREATION, 0) AS QUERY_COUNT_SINCE_CREATION,
    COALESCE(UG.DISTINCT_ROLES_SINCE_CREATION, 0) AS DISTINCT_ROLES_SINCE_CREATION
FROM MART_OBJECTS AS O
INNER JOIN MART_COLUMNS AS C
    ON C.OBJECT_FQN = O.OBJECT_FQN
LEFT JOIN OBJECT_TAG_PIVOT AS OTP
    ON OTP.OBJECT_FQN = O.OBJECT_FQN
LEFT JOIN COLUMN_TAG_PIVOT AS CTP
    ON CTP.OBJECT_FQN = C.OBJECT_FQN
   AND CTP.COLUMN_NAME = C.COLUMN_NAME
LEFT JOIN UPSTREAM_SOURCES AS US
    ON US.OBJECT_FQN = O.OBJECT_FQN
LEFT JOIN DQ_SUMMARY AS DQ
    ON DQ.OBJECT_FQN = O.OBJECT_FQN
LEFT JOIN USAGE_SUMMARY AS UG
    ON UG.OBJECT_FQN = O.OBJECT_FQN;

GRANT SELECT
ON VIEW GOVERNANCE.CATALOG.V_STREAMLIT_CATALOG
TO ROLE CATALOG_APP_ROLE;

SELECT
    OBJECT_FQN,
    COUNT(*) AS COLUMN_ROWS
FROM GOVERNANCE.CATALOG.V_STREAMLIT_CATALOG
GROUP BY OBJECT_FQN
ORDER BY OBJECT_FQN;
