/*==============================================================================
 AVIDIA BANK - STREAMLIT CATALOG VIEW VALIDATION

 Purpose:
   Provide evidence that the Streamlit catalog view is populated from live
   governance metadata rather than dummy application data.
==============================================================================*/

USE ROLE DATA_GOVERNANCE_ADMIN;
USE WAREHOUSE WH_GOVERNANCE_XS;
USE DATABASE GOVERNANCE;
USE SCHEMA CATALOG;

SELECT
    TABLE_CATALOG AS DATABASE_NAME,
    TABLE_SCHEMA AS SCHEMA_NAME,
    TABLE_NAME AS VIEW_NAME
FROM GOVERNANCE.INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'CATALOG'
  AND TABLE_NAME = 'V_STREAMLIT_CATALOG';

SELECT
    COUNT(*) AS TOTAL_CATALOG_ROWS,
    COUNT(DISTINCT OBJECT_FQN) AS TOTAL_OBJECTS,
    COUNT_IF(OBJECT_FQN = 'ANALYTICS.MARTS.DEPOSITS_DAILY') AS DEPOSITS_DAILY_ROWS
FROM GOVERNANCE.CATALOG.V_STREAMLIT_CATALOG;

SELECT
    OBJECT_FQN,
    ANY_VALUE(DATA_OWNER) AS DATA_OWNER,
    ANY_VALUE(DATA_STEWARD) AS DATA_STEWARD,
    ANY_VALUE(DOMAIN) AS DOMAIN,
    ANY_VALUE(CERTIFICATION) AS CERTIFICATION,
    COUNT_IF(CDE_FLAG = 'YES') AS CDE_COLUMN_COUNT,
    COUNT_IF(CLASSIFICATION <> 'NOT CLASSIFIED') AS CLASSIFIED_COLUMN_COUNT,
    ANY_VALUE(UPSTREAM_SOURCES) AS UPSTREAM_SOURCES,
    ANY_VALUE(LAST_REFRESH) AS LAST_REFRESH,
    ANY_VALUE(QUALITY_RESULT) AS QUALITY_RESULT,
    ANY_VALUE(QUERY_COUNT_SINCE_CREATION) AS QUERY_COUNT_SINCE_CREATION,
    ANY_VALUE(DISTINCT_ROLES_SINCE_CREATION) AS DISTINCT_ROLES_SINCE_CREATION
FROM GOVERNANCE.CATALOG.V_STREAMLIT_CATALOG
WHERE OBJECT_FQN = 'ANALYTICS.MARTS.DEPOSITS_DAILY'
GROUP BY OBJECT_FQN;

-- Certification source evidence used by the catalog fallback.
SELECT
    OBJECT_FQN,
    OUTCOME,
    CERTIFIED_AT,
    REQUESTED_AT,
    REQUESTED_BY
FROM GOVERNANCE.EVIDENCE.CERTIFICATION_LOG
WHERE OBJECT_FQN = 'ANALYTICS.MARTS.DEPOSITS_DAILY'
  AND OUTCOME = 'CERTIFIED'
QUALIFY ROW_NUMBER() OVER
(
    ORDER BY COALESCE(CERTIFIED_AT, REQUESTED_AT) DESC,
             CERTIFICATION_RUN_ID DESC
) = 1;

-- Explicit UI readiness check for the primary certified mart.
SELECT
    OBJECT_FQN,
    IFF(ANY_VALUE(DOMAIN) <> 'NOT AVAILABLE', 'PASS', 'FAIL') AS DOMAIN_VISIBLE,
    IFF(ANY_VALUE(DATA_OWNER) <> 'NOT AVAILABLE', 'PASS', 'FAIL') AS OWNER_VISIBLE,
    IFF(ANY_VALUE(DATA_STEWARD) <> 'NOT AVAILABLE', 'PASS', 'FAIL') AS STEWARD_VISIBLE,
    IFF(ANY_VALUE(CERTIFICATION) = 'CERTIFIED', 'PASS', 'FAIL') AS CERTIFICATION_VISIBLE,
    IFF(COUNT_IF(CDE_FLAG = 'YES') > 0, 'PASS', 'FAIL') AS CDE_VISIBLE,
    IFF(COUNT_IF(CLASSIFICATION <> 'NOT CLASSIFIED') > 0, 'PASS', 'FAIL') AS CLASSIFICATION_VISIBLE
FROM GOVERNANCE.CATALOG.V_STREAMLIT_CATALOG
WHERE OBJECT_FQN = 'ANALYTICS.MARTS.DEPOSITS_DAILY'
GROUP BY OBJECT_FQN;

-- Concise interview/demo evidence: one row per governed MART object.
SELECT
    OBJECT_FQN,
    ANY_VALUE(DOMAIN) AS DOMAIN,
    ANY_VALUE(DATA_OWNER) AS DATA_OWNER,
    ANY_VALUE(DATA_STEWARD) AS DATA_STEWARD,
    ANY_VALUE(CERTIFICATION) AS CERTIFICATION,
    COUNT(*) AS COLUMN_COUNT,
    COUNT_IF(DESCRIPTION <> 'NOT AVAILABLE') AS DESCRIBED_COLUMN_COUNT,
    COUNT_IF(CDE_FLAG = 'YES') AS CDE_COLUMN_COUNT,
    COUNT_IF(CLASSIFICATION <> 'NOT CLASSIFIED') AS CLASSIFIED_COLUMN_COUNT,
    ANY_VALUE(QUALITY_RESULT) AS QUALITY_RESULT,
    ANY_VALUE(UPSTREAM_SOURCES) AS UPSTREAM_SOURCES,
    ANY_VALUE(QUERY_COUNT_SINCE_CREATION) AS QUERY_COUNT_SINCE_CREATION,
    ANY_VALUE(DISTINCT_ROLES_SINCE_CREATION) AS DISTINCT_ROLES_SINCE_CREATION
FROM GOVERNANCE.CATALOG.V_STREAMLIT_CATALOG
GROUP BY OBJECT_FQN
ORDER BY OBJECT_FQN;
