-- snow sql -c avidia -f setup/mart/01_prepare_marts_permissions.sql

USE ROLE SECURITYADMIN;

GRANT USAGE
ON WAREHOUSE WH_GOVERNANCE_XS
TO ROLE SVC_PIPELINE_ROLE;

GRANT USAGE
ON DATABASE ANALYTICS
TO ROLE SVC_PIPELINE_ROLE;

GRANT USAGE
ON SCHEMA ANALYTICS.STAGING
TO ROLE SVC_PIPELINE_ROLE;

GRANT SELECT
ON ALL TABLES IN SCHEMA ANALYTICS.STAGING
TO ROLE SVC_PIPELINE_ROLE;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA ANALYTICS.STAGING
TO ROLE SVC_PIPELINE_ROLE;

GRANT SELECT
ON ALL VIEWS IN SCHEMA ANALYTICS.STAGING
TO ROLE SVC_PIPELINE_ROLE;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA ANALYTICS.STAGING
TO ROLE SVC_PIPELINE_ROLE;

GRANT USAGE
ON SCHEMA ANALYTICS.MARTS
TO ROLE SVC_PIPELINE_ROLE;

GRANT CREATE TABLE
ON SCHEMA ANALYTICS.MARTS
TO ROLE SVC_PIPELINE_ROLE;

GRANT CREATE VIEW
ON SCHEMA ANALYTICS.MARTS
TO ROLE SVC_PIPELINE_ROLE;